#!/usr/bin/env python3
"""Generate a block-design-facing wrapper around `axi_n1`.

    python scripts/py/gen_axi_wrap.py -n 5 -o src/synth_top/axi_n1_wrap_5.v

`axi_n1` takes its N slave interfaces as FLATTENED buses (`s_awid[N*ID_W-1:0]`),
which is right for RTL and useless in a block design: Vivado infers an AXI
interface from a port NAMING CONVENTION, so a packed bus arrives as loose wires
and the connection is made by hand, if it is noticed at all. That is the fault
that left the shipped memory mover commandable by nothing.

The wrapper gives each master its own `S00_AXI_*`..`S{N-1}_AXI_*` and the DRAM
side `M00_AXI_*`, with `ASSOCIATED_BUSIF` naming them against their clock.
Nothing else: declarations and assigns.

Per-N because a Verilog port list cannot come from a `generate` block, which is
why this is a script and not a parameter.
"""

import argparse
import sys
from pathlib import Path

#: (signal, width expression or None for 1 bit, direction on a SLAVE port).
#: A master port is the same table with every direction mirrored.
FIELDS = [
    ("awid", "IDW", "i"),
    ("awaddr", "AW", "i"),
    ("awlen", "8", "i"),
    ("awsize", "3", "i"),
    ("awburst", "2", "i"),
    ("awvalid", None, "i"),
    ("awready", None, "o"),
    ("wdata", "DW", "i"),
    ("wstrb", "DW/8", "i"),
    ("wlast", None, "i"),
    ("wvalid", None, "i"),
    ("wready", None, "o"),
    ("bid", "IDW", "o"),
    ("bresp", "2", "o"),
    ("bvalid", None, "o"),
    ("bready", None, "i"),
    ("arid", "IDW", "i"),
    ("araddr", "AW", "i"),
    ("arlen", "8", "i"),
    ("arsize", "3", "i"),
    ("arburst", "2", "i"),
    ("arvalid", None, "i"),
    ("arready", None, "o"),
    ("rid", "IDW", "o"),
    ("rdata", "DW", "o"),
    ("rresp", "2", "o"),
    ("rlast", None, "o"),
    ("rvalid", None, "o"),
    ("rready", None, "i"),
]

#: Signals whose width is the ID, which is wider on the DRAM side: `axi_n1`
#: prepends the master index so responses route without a scoreboard.
ID_FIELDS = {"awid", "bid", "arid", "rid"}


def decls(prefix, mirror, idw):
    """Port declarations for one AXI interface named `prefix`."""
    out = []
    for sig, w, d in FIELDS:
        kind = d if not mirror else ("o" if d == "i" else "i")
        word = "output wire" if kind == "o" else "input  wire"
        width = idw if sig in ID_FIELDS else w
        rng = "" if width is None else f"[{width}-1:0] "
        out.append(f"    {word} {rng}{prefix}_{sig},")
    return "\n".join(out)


def slave_glue(i, prefix):
    """Wire one named slave interface into the packed bus at index `i`."""
    out = []
    for sig, w, d in FIELDS:
        width = "IDW" if sig in ID_FIELDS else w
        if width is None:
            sl = f"[{i}]"
        else:
            sl = f"[{i}*({width}) +: {width}]"
        if d == "i":
            out.append(f"    assign s_{sig}{sl} = {prefix}_{sig};")
        else:
            out.append(f"    assign {prefix}_{sig} = s_{sig}{sl};")
    return "\n".join(out)


def master_glue(prefix):
    """Wire the single named master interface to `axi_n1`'s scalar ports."""
    out = []
    for sig, w, d in FIELDS:
        # `d` is the slave-side direction, so a master port is the mirror: what
        # a slave takes IN, the master drives OUT.
        if d == "i":
            out.append(f"    assign {prefix}_{sig} = m_{sig};")
        else:
            out.append(f"    assign m_{sig} = {prefix}_{sig};")
    return "\n".join(out)


def wires(n):
    """The packed buses between the named ports and `axi_n1`."""
    out = []
    for sig, w, d in FIELDS:
        width = "IDW" if sig in ID_FIELDS else w
        rng = "[N-1:0] " if width is None else f"[N*({width})-1:0] "
        out.append(f"    wire {rng}s_{sig};")
    for sig, w, d in FIELDS:
        width = "SIDW" if sig in ID_FIELDS else w
        rng = "" if width is None else f"[{width}-1:0] "
        out.append(f"    wire {rng}m_{sig};")
    return "\n".join(out)


def emit(n, name, addr_w, data_w, id_w):
    sl_names = [f"S{i:02d}_AXI" for i in range(n)]
    assoc = ":".join(sl_names)
    sl_decls = "\n\n".join(decls(p, False, "IDW") for p in sl_names)
    sl_glue = "\n\n".join(slave_glue(i, p) for i, p in enumerate(sl_names))
    return f"""// {name} -- GENERATED by scripts/py/gen_axi_wrap.py. Do not edit by hand.
//
// {n} AXI4 masters onto one slave across two clocks, with the interfaces named
// so a block design can infer them. The logic is all in axi_n1.v; this file is
// declarations and assigns.
//
// The DRAM side's ID is WIDER than the masters' -- axi_n1 prepends the master
// index so `bid`/`rid` route the response back with no scoreboard. Whatever
// this connects to must carry {id_w} + {max(1, (n - 1).bit_length())} = SIDW id bits.

`default_nettype none

module {name} #(
    parameter integer N    = {n},
    parameter integer AW   = {addr_w},
    parameter integer DW   = {data_w},
    parameter integer IDW  = {id_w},
    parameter integer SIDW = IDW + {max(1, (n - 1).bit_length())}
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF {assoc}, ASSOCIATED_RESET s_aresetn" *)
    input  wire s_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire s_aresetn,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 m_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M00_AXI, ASSOCIATED_RESET m_aresetn" *)
    input  wire m_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 m_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire m_aresetn,

{sl_decls}

{decls("M00_AXI", True, "SIDW")[:-1]}
);
{wires(n)}

{sl_glue}

{master_glue("M00_AXI")}

    axi_n1 #(.N(N), .ADDR_W(AW), .DATA_W(DW), .ID_W(IDW)) u_ic (
        .s_aclk(s_aclk), .s_aresetn(s_aresetn),
        .s_awid(s_awid), .s_awaddr(s_awaddr), .s_awlen(s_awlen),
        .s_awsize(s_awsize), .s_awburst(s_awburst),
        .s_awvalid(s_awvalid), .s_awready(s_awready),
        .s_wdata(s_wdata), .s_wstrb(s_wstrb), .s_wlast(s_wlast),
        .s_wvalid(s_wvalid), .s_wready(s_wready),
        .s_bid(s_bid), .s_bresp(s_bresp), .s_bvalid(s_bvalid),
        .s_bready(s_bready),
        .s_arid(s_arid), .s_araddr(s_araddr), .s_arlen(s_arlen),
        .s_arsize(s_arsize), .s_arburst(s_arburst),
        .s_arvalid(s_arvalid), .s_arready(s_arready),
        .s_rid(s_rid), .s_rdata(s_rdata), .s_rresp(s_rresp),
        .s_rlast(s_rlast), .s_rvalid(s_rvalid), .s_rready(s_rready),
        .m_aclk(m_aclk), .m_aresetn(m_aresetn),
        .m_awid(m_awid), .m_awaddr(m_awaddr), .m_awlen(m_awlen),
        .m_awsize(m_awsize), .m_awburst(m_awburst),
        .m_awvalid(m_awvalid), .m_awready(m_awready),
        .m_wdata(m_wdata), .m_wstrb(m_wstrb), .m_wlast(m_wlast),
        .m_wvalid(m_wvalid), .m_wready(m_wready),
        .m_bid(m_bid), .m_bresp(m_bresp), .m_bvalid(m_bvalid),
        .m_bready(m_bready),
        .m_arid(m_arid), .m_araddr(m_araddr), .m_arlen(m_arlen),
        .m_arsize(m_arsize), .m_arburst(m_arburst),
        .m_arvalid(m_arvalid), .m_arready(m_arready),
        .m_rid(m_rid), .m_rdata(m_rdata), .m_rresp(m_rresp),
        .m_rlast(m_rlast), .m_rvalid(m_rvalid), .m_rready(m_rready)
    );

endmodule

`default_nettype wire
"""


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("-n", "--masters", type=int, required=True)
    ap.add_argument("-o", "--out", help="output .v (default: stdout)")
    ap.add_argument("-m", "--module", help="module name (default: axi_n1_wrap_<N>)")
    ap.add_argument("--addr", type=int, default=34)
    ap.add_argument("--data", type=int, default=256)
    ap.add_argument("--id", type=int, default=4)
    args = ap.parse_args()

    if args.masters < 1:
        sys.exit("gen_axi_wrap: need at least one master")
    name = args.module or f"axi_n1_wrap_{args.masters}"
    text = emit(args.masters, name, args.addr, args.data, args.id)

    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(
            f"{args.out}: {args.masters} slave interfaces + M00_AXI, "
            f"{args.data}b/{args.addr}a, id {args.id} -> "
            f"{args.id + max(1, (args.masters - 1).bit_length())}"
        )
    else:
        print(text)


if __name__ == "__main__":
    main()
