// axi_n1_wrap_5 -- GENERATED by scripts/py/gen_axi_wrap.py. Do not edit by hand.
//
// 5 AXI4 masters onto one slave across two clocks, with the interfaces named
// so a block design can infer them. The logic is all in axi_n1.v; this file is
// declarations and assigns.
//
// The DRAM side's ID is WIDER than the masters' -- axi_n1 prepends the master
// index so `bid`/`rid` route the response back with no scoreboard. Whatever
// this connects to must carry 4 + 3 = SIDW id bits.

`default_nettype none

module axi_n1_wrap_5 #(
    parameter integer N    = 5,
    parameter integer AW   = 34,
    parameter integer DW   = 256,
    parameter integer IDW  = 4,
    parameter integer SIDW = IDW + 3
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S00_AXI:S01_AXI:S02_AXI:S03_AXI:S04_AXI, ASSOCIATED_RESET s_aresetn" *)
    input  wire s_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire s_aresetn,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 m_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M00_AXI, ASSOCIATED_RESET m_aresetn" *)
    input  wire m_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 m_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire m_aresetn,

    input  wire [IDW-1:0] S00_AXI_awid,
    input  wire [AW-1:0] S00_AXI_awaddr,
    input  wire [8-1:0] S00_AXI_awlen,
    input  wire [3-1:0] S00_AXI_awsize,
    input  wire [2-1:0] S00_AXI_awburst,
    input  wire S00_AXI_awvalid,
    output wire S00_AXI_awready,
    input  wire [DW-1:0] S00_AXI_wdata,
    input  wire [DW/8-1:0] S00_AXI_wstrb,
    input  wire S00_AXI_wlast,
    input  wire S00_AXI_wvalid,
    output wire S00_AXI_wready,
    output wire [IDW-1:0] S00_AXI_bid,
    output wire [2-1:0] S00_AXI_bresp,
    output wire S00_AXI_bvalid,
    input  wire S00_AXI_bready,
    input  wire [IDW-1:0] S00_AXI_arid,
    input  wire [AW-1:0] S00_AXI_araddr,
    input  wire [8-1:0] S00_AXI_arlen,
    input  wire [3-1:0] S00_AXI_arsize,
    input  wire [2-1:0] S00_AXI_arburst,
    input  wire S00_AXI_arvalid,
    output wire S00_AXI_arready,
    output wire [IDW-1:0] S00_AXI_rid,
    output wire [DW-1:0] S00_AXI_rdata,
    output wire [2-1:0] S00_AXI_rresp,
    output wire S00_AXI_rlast,
    output wire S00_AXI_rvalid,
    input  wire S00_AXI_rready,

    input  wire [IDW-1:0] S01_AXI_awid,
    input  wire [AW-1:0] S01_AXI_awaddr,
    input  wire [8-1:0] S01_AXI_awlen,
    input  wire [3-1:0] S01_AXI_awsize,
    input  wire [2-1:0] S01_AXI_awburst,
    input  wire S01_AXI_awvalid,
    output wire S01_AXI_awready,
    input  wire [DW-1:0] S01_AXI_wdata,
    input  wire [DW/8-1:0] S01_AXI_wstrb,
    input  wire S01_AXI_wlast,
    input  wire S01_AXI_wvalid,
    output wire S01_AXI_wready,
    output wire [IDW-1:0] S01_AXI_bid,
    output wire [2-1:0] S01_AXI_bresp,
    output wire S01_AXI_bvalid,
    input  wire S01_AXI_bready,
    input  wire [IDW-1:0] S01_AXI_arid,
    input  wire [AW-1:0] S01_AXI_araddr,
    input  wire [8-1:0] S01_AXI_arlen,
    input  wire [3-1:0] S01_AXI_arsize,
    input  wire [2-1:0] S01_AXI_arburst,
    input  wire S01_AXI_arvalid,
    output wire S01_AXI_arready,
    output wire [IDW-1:0] S01_AXI_rid,
    output wire [DW-1:0] S01_AXI_rdata,
    output wire [2-1:0] S01_AXI_rresp,
    output wire S01_AXI_rlast,
    output wire S01_AXI_rvalid,
    input  wire S01_AXI_rready,

    input  wire [IDW-1:0] S02_AXI_awid,
    input  wire [AW-1:0] S02_AXI_awaddr,
    input  wire [8-1:0] S02_AXI_awlen,
    input  wire [3-1:0] S02_AXI_awsize,
    input  wire [2-1:0] S02_AXI_awburst,
    input  wire S02_AXI_awvalid,
    output wire S02_AXI_awready,
    input  wire [DW-1:0] S02_AXI_wdata,
    input  wire [DW/8-1:0] S02_AXI_wstrb,
    input  wire S02_AXI_wlast,
    input  wire S02_AXI_wvalid,
    output wire S02_AXI_wready,
    output wire [IDW-1:0] S02_AXI_bid,
    output wire [2-1:0] S02_AXI_bresp,
    output wire S02_AXI_bvalid,
    input  wire S02_AXI_bready,
    input  wire [IDW-1:0] S02_AXI_arid,
    input  wire [AW-1:0] S02_AXI_araddr,
    input  wire [8-1:0] S02_AXI_arlen,
    input  wire [3-1:0] S02_AXI_arsize,
    input  wire [2-1:0] S02_AXI_arburst,
    input  wire S02_AXI_arvalid,
    output wire S02_AXI_arready,
    output wire [IDW-1:0] S02_AXI_rid,
    output wire [DW-1:0] S02_AXI_rdata,
    output wire [2-1:0] S02_AXI_rresp,
    output wire S02_AXI_rlast,
    output wire S02_AXI_rvalid,
    input  wire S02_AXI_rready,

    input  wire [IDW-1:0] S03_AXI_awid,
    input  wire [AW-1:0] S03_AXI_awaddr,
    input  wire [8-1:0] S03_AXI_awlen,
    input  wire [3-1:0] S03_AXI_awsize,
    input  wire [2-1:0] S03_AXI_awburst,
    input  wire S03_AXI_awvalid,
    output wire S03_AXI_awready,
    input  wire [DW-1:0] S03_AXI_wdata,
    input  wire [DW/8-1:0] S03_AXI_wstrb,
    input  wire S03_AXI_wlast,
    input  wire S03_AXI_wvalid,
    output wire S03_AXI_wready,
    output wire [IDW-1:0] S03_AXI_bid,
    output wire [2-1:0] S03_AXI_bresp,
    output wire S03_AXI_bvalid,
    input  wire S03_AXI_bready,
    input  wire [IDW-1:0] S03_AXI_arid,
    input  wire [AW-1:0] S03_AXI_araddr,
    input  wire [8-1:0] S03_AXI_arlen,
    input  wire [3-1:0] S03_AXI_arsize,
    input  wire [2-1:0] S03_AXI_arburst,
    input  wire S03_AXI_arvalid,
    output wire S03_AXI_arready,
    output wire [IDW-1:0] S03_AXI_rid,
    output wire [DW-1:0] S03_AXI_rdata,
    output wire [2-1:0] S03_AXI_rresp,
    output wire S03_AXI_rlast,
    output wire S03_AXI_rvalid,
    input  wire S03_AXI_rready,

    input  wire [IDW-1:0] S04_AXI_awid,
    input  wire [AW-1:0] S04_AXI_awaddr,
    input  wire [8-1:0] S04_AXI_awlen,
    input  wire [3-1:0] S04_AXI_awsize,
    input  wire [2-1:0] S04_AXI_awburst,
    input  wire S04_AXI_awvalid,
    output wire S04_AXI_awready,
    input  wire [DW-1:0] S04_AXI_wdata,
    input  wire [DW/8-1:0] S04_AXI_wstrb,
    input  wire S04_AXI_wlast,
    input  wire S04_AXI_wvalid,
    output wire S04_AXI_wready,
    output wire [IDW-1:0] S04_AXI_bid,
    output wire [2-1:0] S04_AXI_bresp,
    output wire S04_AXI_bvalid,
    input  wire S04_AXI_bready,
    input  wire [IDW-1:0] S04_AXI_arid,
    input  wire [AW-1:0] S04_AXI_araddr,
    input  wire [8-1:0] S04_AXI_arlen,
    input  wire [3-1:0] S04_AXI_arsize,
    input  wire [2-1:0] S04_AXI_arburst,
    input  wire S04_AXI_arvalid,
    output wire S04_AXI_arready,
    output wire [IDW-1:0] S04_AXI_rid,
    output wire [DW-1:0] S04_AXI_rdata,
    output wire [2-1:0] S04_AXI_rresp,
    output wire S04_AXI_rlast,
    output wire S04_AXI_rvalid,
    input  wire S04_AXI_rready,

    output wire [SIDW-1:0] M00_AXI_awid,
    output wire [AW-1:0] M00_AXI_awaddr,
    output wire [8-1:0] M00_AXI_awlen,
    output wire [3-1:0] M00_AXI_awsize,
    output wire [2-1:0] M00_AXI_awburst,
    output wire M00_AXI_awvalid,
    input  wire M00_AXI_awready,
    output wire [DW-1:0] M00_AXI_wdata,
    output wire [DW/8-1:0] M00_AXI_wstrb,
    output wire M00_AXI_wlast,
    output wire M00_AXI_wvalid,
    input  wire M00_AXI_wready,
    input  wire [SIDW-1:0] M00_AXI_bid,
    input  wire [2-1:0] M00_AXI_bresp,
    input  wire M00_AXI_bvalid,
    output wire M00_AXI_bready,
    output wire [SIDW-1:0] M00_AXI_arid,
    output wire [AW-1:0] M00_AXI_araddr,
    output wire [8-1:0] M00_AXI_arlen,
    output wire [3-1:0] M00_AXI_arsize,
    output wire [2-1:0] M00_AXI_arburst,
    output wire M00_AXI_arvalid,
    input  wire M00_AXI_arready,
    input  wire [SIDW-1:0] M00_AXI_rid,
    input  wire [DW-1:0] M00_AXI_rdata,
    input  wire [2-1:0] M00_AXI_rresp,
    input  wire M00_AXI_rlast,
    input  wire M00_AXI_rvalid,
    output wire M00_AXI_rready
);
    wire [N*(IDW)-1:0] s_awid;
    wire [N*(AW)-1:0] s_awaddr;
    wire [N*(8)-1:0] s_awlen;
    wire [N*(3)-1:0] s_awsize;
    wire [N*(2)-1:0] s_awburst;
    wire [N-1:0] s_awvalid;
    wire [N-1:0] s_awready;
    wire [N*(DW)-1:0] s_wdata;
    wire [N*(DW/8)-1:0] s_wstrb;
    wire [N-1:0] s_wlast;
    wire [N-1:0] s_wvalid;
    wire [N-1:0] s_wready;
    wire [N*(IDW)-1:0] s_bid;
    wire [N*(2)-1:0] s_bresp;
    wire [N-1:0] s_bvalid;
    wire [N-1:0] s_bready;
    wire [N*(IDW)-1:0] s_arid;
    wire [N*(AW)-1:0] s_araddr;
    wire [N*(8)-1:0] s_arlen;
    wire [N*(3)-1:0] s_arsize;
    wire [N*(2)-1:0] s_arburst;
    wire [N-1:0] s_arvalid;
    wire [N-1:0] s_arready;
    wire [N*(IDW)-1:0] s_rid;
    wire [N*(DW)-1:0] s_rdata;
    wire [N*(2)-1:0] s_rresp;
    wire [N-1:0] s_rlast;
    wire [N-1:0] s_rvalid;
    wire [N-1:0] s_rready;
    wire [SIDW-1:0] m_awid;
    wire [AW-1:0] m_awaddr;
    wire [8-1:0] m_awlen;
    wire [3-1:0] m_awsize;
    wire [2-1:0] m_awburst;
    wire m_awvalid;
    wire m_awready;
    wire [DW-1:0] m_wdata;
    wire [DW/8-1:0] m_wstrb;
    wire m_wlast;
    wire m_wvalid;
    wire m_wready;
    wire [SIDW-1:0] m_bid;
    wire [2-1:0] m_bresp;
    wire m_bvalid;
    wire m_bready;
    wire [SIDW-1:0] m_arid;
    wire [AW-1:0] m_araddr;
    wire [8-1:0] m_arlen;
    wire [3-1:0] m_arsize;
    wire [2-1:0] m_arburst;
    wire m_arvalid;
    wire m_arready;
    wire [SIDW-1:0] m_rid;
    wire [DW-1:0] m_rdata;
    wire [2-1:0] m_rresp;
    wire m_rlast;
    wire m_rvalid;
    wire m_rready;

    assign s_awid[0*(IDW) +: IDW] = S00_AXI_awid;
    assign s_awaddr[0*(AW) +: AW] = S00_AXI_awaddr;
    assign s_awlen[0*(8) +: 8] = S00_AXI_awlen;
    assign s_awsize[0*(3) +: 3] = S00_AXI_awsize;
    assign s_awburst[0*(2) +: 2] = S00_AXI_awburst;
    assign s_awvalid[0] = S00_AXI_awvalid;
    assign S00_AXI_awready = s_awready[0];
    assign s_wdata[0*(DW) +: DW] = S00_AXI_wdata;
    assign s_wstrb[0*(DW/8) +: DW/8] = S00_AXI_wstrb;
    assign s_wlast[0] = S00_AXI_wlast;
    assign s_wvalid[0] = S00_AXI_wvalid;
    assign S00_AXI_wready = s_wready[0];
    assign S00_AXI_bid = s_bid[0*(IDW) +: IDW];
    assign S00_AXI_bresp = s_bresp[0*(2) +: 2];
    assign S00_AXI_bvalid = s_bvalid[0];
    assign s_bready[0] = S00_AXI_bready;
    assign s_arid[0*(IDW) +: IDW] = S00_AXI_arid;
    assign s_araddr[0*(AW) +: AW] = S00_AXI_araddr;
    assign s_arlen[0*(8) +: 8] = S00_AXI_arlen;
    assign s_arsize[0*(3) +: 3] = S00_AXI_arsize;
    assign s_arburst[0*(2) +: 2] = S00_AXI_arburst;
    assign s_arvalid[0] = S00_AXI_arvalid;
    assign S00_AXI_arready = s_arready[0];
    assign S00_AXI_rid = s_rid[0*(IDW) +: IDW];
    assign S00_AXI_rdata = s_rdata[0*(DW) +: DW];
    assign S00_AXI_rresp = s_rresp[0*(2) +: 2];
    assign S00_AXI_rlast = s_rlast[0];
    assign S00_AXI_rvalid = s_rvalid[0];
    assign s_rready[0] = S00_AXI_rready;

    assign s_awid[1*(IDW) +: IDW] = S01_AXI_awid;
    assign s_awaddr[1*(AW) +: AW] = S01_AXI_awaddr;
    assign s_awlen[1*(8) +: 8] = S01_AXI_awlen;
    assign s_awsize[1*(3) +: 3] = S01_AXI_awsize;
    assign s_awburst[1*(2) +: 2] = S01_AXI_awburst;
    assign s_awvalid[1] = S01_AXI_awvalid;
    assign S01_AXI_awready = s_awready[1];
    assign s_wdata[1*(DW) +: DW] = S01_AXI_wdata;
    assign s_wstrb[1*(DW/8) +: DW/8] = S01_AXI_wstrb;
    assign s_wlast[1] = S01_AXI_wlast;
    assign s_wvalid[1] = S01_AXI_wvalid;
    assign S01_AXI_wready = s_wready[1];
    assign S01_AXI_bid = s_bid[1*(IDW) +: IDW];
    assign S01_AXI_bresp = s_bresp[1*(2) +: 2];
    assign S01_AXI_bvalid = s_bvalid[1];
    assign s_bready[1] = S01_AXI_bready;
    assign s_arid[1*(IDW) +: IDW] = S01_AXI_arid;
    assign s_araddr[1*(AW) +: AW] = S01_AXI_araddr;
    assign s_arlen[1*(8) +: 8] = S01_AXI_arlen;
    assign s_arsize[1*(3) +: 3] = S01_AXI_arsize;
    assign s_arburst[1*(2) +: 2] = S01_AXI_arburst;
    assign s_arvalid[1] = S01_AXI_arvalid;
    assign S01_AXI_arready = s_arready[1];
    assign S01_AXI_rid = s_rid[1*(IDW) +: IDW];
    assign S01_AXI_rdata = s_rdata[1*(DW) +: DW];
    assign S01_AXI_rresp = s_rresp[1*(2) +: 2];
    assign S01_AXI_rlast = s_rlast[1];
    assign S01_AXI_rvalid = s_rvalid[1];
    assign s_rready[1] = S01_AXI_rready;

    assign s_awid[2*(IDW) +: IDW] = S02_AXI_awid;
    assign s_awaddr[2*(AW) +: AW] = S02_AXI_awaddr;
    assign s_awlen[2*(8) +: 8] = S02_AXI_awlen;
    assign s_awsize[2*(3) +: 3] = S02_AXI_awsize;
    assign s_awburst[2*(2) +: 2] = S02_AXI_awburst;
    assign s_awvalid[2] = S02_AXI_awvalid;
    assign S02_AXI_awready = s_awready[2];
    assign s_wdata[2*(DW) +: DW] = S02_AXI_wdata;
    assign s_wstrb[2*(DW/8) +: DW/8] = S02_AXI_wstrb;
    assign s_wlast[2] = S02_AXI_wlast;
    assign s_wvalid[2] = S02_AXI_wvalid;
    assign S02_AXI_wready = s_wready[2];
    assign S02_AXI_bid = s_bid[2*(IDW) +: IDW];
    assign S02_AXI_bresp = s_bresp[2*(2) +: 2];
    assign S02_AXI_bvalid = s_bvalid[2];
    assign s_bready[2] = S02_AXI_bready;
    assign s_arid[2*(IDW) +: IDW] = S02_AXI_arid;
    assign s_araddr[2*(AW) +: AW] = S02_AXI_araddr;
    assign s_arlen[2*(8) +: 8] = S02_AXI_arlen;
    assign s_arsize[2*(3) +: 3] = S02_AXI_arsize;
    assign s_arburst[2*(2) +: 2] = S02_AXI_arburst;
    assign s_arvalid[2] = S02_AXI_arvalid;
    assign S02_AXI_arready = s_arready[2];
    assign S02_AXI_rid = s_rid[2*(IDW) +: IDW];
    assign S02_AXI_rdata = s_rdata[2*(DW) +: DW];
    assign S02_AXI_rresp = s_rresp[2*(2) +: 2];
    assign S02_AXI_rlast = s_rlast[2];
    assign S02_AXI_rvalid = s_rvalid[2];
    assign s_rready[2] = S02_AXI_rready;

    assign s_awid[3*(IDW) +: IDW] = S03_AXI_awid;
    assign s_awaddr[3*(AW) +: AW] = S03_AXI_awaddr;
    assign s_awlen[3*(8) +: 8] = S03_AXI_awlen;
    assign s_awsize[3*(3) +: 3] = S03_AXI_awsize;
    assign s_awburst[3*(2) +: 2] = S03_AXI_awburst;
    assign s_awvalid[3] = S03_AXI_awvalid;
    assign S03_AXI_awready = s_awready[3];
    assign s_wdata[3*(DW) +: DW] = S03_AXI_wdata;
    assign s_wstrb[3*(DW/8) +: DW/8] = S03_AXI_wstrb;
    assign s_wlast[3] = S03_AXI_wlast;
    assign s_wvalid[3] = S03_AXI_wvalid;
    assign S03_AXI_wready = s_wready[3];
    assign S03_AXI_bid = s_bid[3*(IDW) +: IDW];
    assign S03_AXI_bresp = s_bresp[3*(2) +: 2];
    assign S03_AXI_bvalid = s_bvalid[3];
    assign s_bready[3] = S03_AXI_bready;
    assign s_arid[3*(IDW) +: IDW] = S03_AXI_arid;
    assign s_araddr[3*(AW) +: AW] = S03_AXI_araddr;
    assign s_arlen[3*(8) +: 8] = S03_AXI_arlen;
    assign s_arsize[3*(3) +: 3] = S03_AXI_arsize;
    assign s_arburst[3*(2) +: 2] = S03_AXI_arburst;
    assign s_arvalid[3] = S03_AXI_arvalid;
    assign S03_AXI_arready = s_arready[3];
    assign S03_AXI_rid = s_rid[3*(IDW) +: IDW];
    assign S03_AXI_rdata = s_rdata[3*(DW) +: DW];
    assign S03_AXI_rresp = s_rresp[3*(2) +: 2];
    assign S03_AXI_rlast = s_rlast[3];
    assign S03_AXI_rvalid = s_rvalid[3];
    assign s_rready[3] = S03_AXI_rready;

    assign s_awid[4*(IDW) +: IDW] = S04_AXI_awid;
    assign s_awaddr[4*(AW) +: AW] = S04_AXI_awaddr;
    assign s_awlen[4*(8) +: 8] = S04_AXI_awlen;
    assign s_awsize[4*(3) +: 3] = S04_AXI_awsize;
    assign s_awburst[4*(2) +: 2] = S04_AXI_awburst;
    assign s_awvalid[4] = S04_AXI_awvalid;
    assign S04_AXI_awready = s_awready[4];
    assign s_wdata[4*(DW) +: DW] = S04_AXI_wdata;
    assign s_wstrb[4*(DW/8) +: DW/8] = S04_AXI_wstrb;
    assign s_wlast[4] = S04_AXI_wlast;
    assign s_wvalid[4] = S04_AXI_wvalid;
    assign S04_AXI_wready = s_wready[4];
    assign S04_AXI_bid = s_bid[4*(IDW) +: IDW];
    assign S04_AXI_bresp = s_bresp[4*(2) +: 2];
    assign S04_AXI_bvalid = s_bvalid[4];
    assign s_bready[4] = S04_AXI_bready;
    assign s_arid[4*(IDW) +: IDW] = S04_AXI_arid;
    assign s_araddr[4*(AW) +: AW] = S04_AXI_araddr;
    assign s_arlen[4*(8) +: 8] = S04_AXI_arlen;
    assign s_arsize[4*(3) +: 3] = S04_AXI_arsize;
    assign s_arburst[4*(2) +: 2] = S04_AXI_arburst;
    assign s_arvalid[4] = S04_AXI_arvalid;
    assign S04_AXI_arready = s_arready[4];
    assign S04_AXI_rid = s_rid[4*(IDW) +: IDW];
    assign S04_AXI_rdata = s_rdata[4*(DW) +: DW];
    assign S04_AXI_rresp = s_rresp[4*(2) +: 2];
    assign S04_AXI_rlast = s_rlast[4];
    assign S04_AXI_rvalid = s_rvalid[4];
    assign s_rready[4] = S04_AXI_rready;

    assign M00_AXI_awid = m_awid;
    assign M00_AXI_awaddr = m_awaddr;
    assign M00_AXI_awlen = m_awlen;
    assign M00_AXI_awsize = m_awsize;
    assign M00_AXI_awburst = m_awburst;
    assign M00_AXI_awvalid = m_awvalid;
    assign m_awready = M00_AXI_awready;
    assign M00_AXI_wdata = m_wdata;
    assign M00_AXI_wstrb = m_wstrb;
    assign M00_AXI_wlast = m_wlast;
    assign M00_AXI_wvalid = m_wvalid;
    assign m_wready = M00_AXI_wready;
    assign m_bid = M00_AXI_bid;
    assign m_bresp = M00_AXI_bresp;
    assign m_bvalid = M00_AXI_bvalid;
    assign M00_AXI_bready = m_bready;
    assign M00_AXI_arid = m_arid;
    assign M00_AXI_araddr = m_araddr;
    assign M00_AXI_arlen = m_arlen;
    assign M00_AXI_arsize = m_arsize;
    assign M00_AXI_arburst = m_arburst;
    assign M00_AXI_arvalid = m_arvalid;
    assign m_arready = M00_AXI_arready;
    assign m_rid = M00_AXI_rid;
    assign m_rdata = M00_AXI_rdata;
    assign m_rresp = M00_AXI_rresp;
    assign m_rlast = M00_AXI_rlast;
    assign m_rvalid = M00_AXI_rvalid;
    assign M00_AXI_rready = m_rready;

    axi_n1 #(.N(N), .ADDR_W(AW), .DATA_W(DW), .ID_W(IDW)) u_ic (
        .s_aclk(s_aclk), .s_aresetn(s_aresetn),
        .s_awid(s_awid), .s_awaddr(s_awaddr), .s_awlen(s_awlen),
        .s_awsize(s_awsize), .s_awburst(s_awburst),
        .s_awvalid(s_awvalid), .s_awready(s_awready),
        .s_wdata(s_wdata), .s_wstrb(s_wstrb), .s_wlast(s_wlast),
        .s_wvalid(s_wvalid), .s_wready(s_wready),
        .s_bid(s_bid), .s_bresp(s_bresp), .s_bvalid(s_bvalid),
        .s_bready(s_bready),
        .s_arid(s_arid), .s_araddr(s_araddr), .s_arlen(s_arlen),
        .s_arsize(s_arsize), .s_arburst(s_arburst),
        .s_arvalid(s_arvalid), .s_arready(s_arready),
        .s_rid(s_rid), .s_rdata(s_rdata), .s_rresp(s_rresp),
        .s_rlast(s_rlast), .s_rvalid(s_rvalid), .s_rready(s_rready),
        .m_aclk(m_aclk), .m_aresetn(m_aresetn),
        .m_awid(m_awid), .m_awaddr(m_awaddr), .m_awlen(m_awlen),
        .m_awsize(m_awsize), .m_awburst(m_awburst),
        .m_awvalid(m_awvalid), .m_awready(m_awready),
        .m_wdata(m_wdata), .m_wstrb(m_wstrb), .m_wlast(m_wlast),
        .m_wvalid(m_wvalid), .m_wready(m_wready),
        .m_bid(m_bid), .m_bresp(m_bresp), .m_bvalid(m_bvalid),
        .m_bready(m_bready),
        .m_arid(m_arid), .m_araddr(m_araddr), .m_arlen(m_arlen),
        .m_arsize(m_arsize), .m_arburst(m_arburst),
        .m_arvalid(m_arvalid), .m_arready(m_arready),
        .m_rid(m_rid), .m_rdata(m_rdata), .m_rresp(m_rresp),
        .m_rlast(m_rlast), .m_rvalid(m_rvalid), .m_rready(m_rready)
    );

endmodule

`default_nettype wire
