// ktpu_ship_2x2_6c2v_1m -- GENERATED by scripts/py/gen_mesh.py. Do not edit by hand.
//
//   xxx mat vec xxx
//   mag mat mat xxx
//   mag mat mat xxx
//   xxx mat vec xxx
//
// 2x2 routers, 2 MAG port(s), 6 cluster(s), 2 vector core(s).
// GRID_X_HI=2 GRID_Y_HI=2: the clamp is per axis, so the grid need not
// be square. Edge endpoints live outside the router grid and are reached by it.
//
// MAG presents 1 = 1 AXI masters -- one per memory port, plus the
// host upload and the memory mover, plus the interlink's landing channel. Merge them with one SmartConnect in the
// block design; hand-written arbitration here would duplicate it badly.
//
// INTERLINK ON. Two full-duplex links: M_AXIS_LINKn out, S_AXIS_LINKn in.
// link0 flips the mesh's x, link1 flips its y (mag_switch.v).
// TREADY MUST NOT CROSS AN SLR. The far end has to be another mesh's
// S_AXIS_LINK, whose tready is tied high; a real slave there reintroduces the
// combinational SLR crossing mag_link.v exists to avoid.

`default_nettype none

module ktpu_ship_2x2_6c2v_1m #(
    parameter integer FW       = 288,
    parameter integer PW       = 4,
    parameter integer DW       = 256,
    parameter integer AW       = 34,
    parameter integer IDW      = 4,
    parameter integer NM       = 1,
    // The MEMORY's beat. mag_1m packs DW up to this before the
    // boundary, so the mesh never exposes the internal width.
    parameter integer MW       = 512,
    // One flit per beat at 288, so a packet's framing is its own length; 96
    // is mag.v's TUSER_W.
    parameter integer LKW      = 288,
    parameter integer LKU      = 96,
    // Only the RESET value -- IL_MESH is writable, so the four instances of
    // this module differ by this parameter alone.
    parameter integer MESH_ID  = 0,
    parameter integer MODEL    = 0,
    parameter integer L1_DEPTH = 512,
    // src/ktpu/hw/bench.py's TILES / L1_A_ENTRIES / L1_B_ENTRIES. A generated
    // top that omits them elaborates mx_cluster_cu's 256/32/32 instead.
    // 4096 in URAM, not 512 in BRAM: width sets the primitive count (5 either
    // way) so depth is free, and gm*gn<=TILES bounds arithmetic intensity --
    // 21.3 at 512 against 64.0 at 4096.
    parameter integer TILES    = 4096,
    // mx_acu_fp is already READ_LAT=2, so "ultra" needs no pipeline change.
    parameter         TILE_PRIM = "ultra",
    // BLOCK, not ultra. vec_core supports either, but at L1_DEPTH=512 URAM
    // saves 4 BRAM per core and costs a cycle on every VLD and VDRAIN -- and
    // the vector core is schedule-bound, not capacity-bound. Worth revisiting
    // only once rd_req_tag/rr_tag widen past 9 bits and depth 4096 is real.
    parameter         VEC_PRIM  = "block",
    // 512/512, NOT the compiler's 128/256: capacity is an upper bound the
    // planner need not fill, and at 928 bits wide the BRAM cost is set by
    // WIDTH -- 13 RAMB36 per port at any depth to 512 -- so the extra is free.
    // 512 needs the L1 BANK BIT, because aoff/boff are 8-bit fields: the
    // address is the bank concatenated with the offset, and the bank is
    // CU_INST [114]/[113]/[112] -- docs/isa/cluster.md s4.6. Two banks is the
    // ceiling; deeper needs a second bit, which mx_cluster_mgr reports.
    parameter integer GA       = 512,
    parameter integer GB       = 512,
    // MUST be "block" at these depths: 512 x 928 bits of LUTRAM per port is
    // ~100k LUT per cluster. The two parameters are not independent.
    parameter         L1_PRIM  = "block",
    // 512 BECAUSE THE DEPTH IS ALREADY PAID FOR. A 288-bit FIFO is 4 RAMB36 at
    // any depth to 512, so the old 32/64 used 6%/12% of their own tiles.
    // Measured on noc_cu_base: 8 BRAM either way, +34 LUT, 574 -> 567 MHz.
    parameter integer INST_DEPTH = 512,
    parameter integer RECV_DEPTH = 512
)(
    // One clock and one reset for every interface, master and slave alike, so
    // neither carries an s_ or m_ prefix. ASSOCIATED_BUSIF names them all, which
    // is what makes the block design tie them up on its own.
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 axi_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S_AXI_MEM:S_AXI_CTRL:M_AXIS_LINK0:S_AXIS_LINK0:M_AXIS_LINK1:S_AXIS_LINK1, ASSOCIATED_RESET axi_aresetn" *)
    input  wire axi_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 axi_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire axi_aresetn,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 dram_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M_AXI_DRAM, ASSOCIATED_RESET dram_aresetn" *)
    input  wire dram_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 dram_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire dram_aresetn,

    input  wire [IDW-1:0]   S_AXI_MEM_awid,
    input  wire [AW-1:0]    S_AXI_MEM_awaddr,
    input  wire [7:0]       S_AXI_MEM_awlen,
    input  wire             S_AXI_MEM_awvalid,
    output wire             S_AXI_MEM_awready,
    input  wire [DW-1:0]    S_AXI_MEM_wdata,
    input  wire [DW/8-1:0]  S_AXI_MEM_wstrb,
    input  wire             S_AXI_MEM_wlast,
    input  wire             S_AXI_MEM_wvalid,
    output wire             S_AXI_MEM_wready,
    output wire [IDW-1:0]   S_AXI_MEM_bid,
    output wire [1:0]       S_AXI_MEM_bresp,
    output wire             S_AXI_MEM_bvalid,
    input  wire             S_AXI_MEM_bready,
    input  wire [IDW-1:0]   S_AXI_MEM_arid,
    input  wire [AW-1:0]    S_AXI_MEM_araddr,
    input  wire [7:0]       S_AXI_MEM_arlen,
    input  wire             S_AXI_MEM_arvalid,
    output wire             S_AXI_MEM_arready,
    output wire [IDW-1:0]   S_AXI_MEM_rid,
    output wire [DW-1:0]    S_AXI_MEM_rdata,
    output wire [1:0]       S_AXI_MEM_rresp,
    output wire             S_AXI_MEM_rlast,
    output wire             S_AXI_MEM_rvalid,
    input  wire             S_AXI_MEM_rready,

    input  wire [IDW-1:0]   S_AXI_CTRL_awid,
    input  wire [31:0]      S_AXI_CTRL_awaddr,
    input  wire [7:0]       S_AXI_CTRL_awlen,
    input  wire             S_AXI_CTRL_awvalid,
    output wire             S_AXI_CTRL_awready,
    input  wire [63:0]      S_AXI_CTRL_wdata,
    input  wire [7:0]       S_AXI_CTRL_wstrb,
    input  wire             S_AXI_CTRL_wlast,
    input  wire             S_AXI_CTRL_wvalid,
    output wire             S_AXI_CTRL_wready,
    output wire [IDW-1:0]   S_AXI_CTRL_bid,
    output wire [1:0]       S_AXI_CTRL_bresp,
    output wire             S_AXI_CTRL_bvalid,
    input  wire             S_AXI_CTRL_bready,
    input  wire [IDW-1:0]   S_AXI_CTRL_arid,
    input  wire [31:0]      S_AXI_CTRL_araddr,
    input  wire [7:0]       S_AXI_CTRL_arlen,
    input  wire             S_AXI_CTRL_arvalid,
    output wire             S_AXI_CTRL_arready,
    output wire [IDW-1:0]   S_AXI_CTRL_rid,
    output wire [63:0]      S_AXI_CTRL_rdata,
    output wire [1:0]       S_AXI_CTRL_rresp,
    output wire             S_AXI_CTRL_rlast,
    output wire             S_AXI_CTRL_rvalid,
    input  wire             S_AXI_CTRL_rready,

    // ---- M_AXI_DRAM ----
    output wire [IDW-1:0] M_AXI_DRAM_awid,
    output wire [AW-1:0] M_AXI_DRAM_awaddr,
    output wire [8-1:0] M_AXI_DRAM_awlen,
    output wire [3-1:0] M_AXI_DRAM_awsize,
    output wire [2-1:0] M_AXI_DRAM_awburst,
    output wire M_AXI_DRAM_awvalid,
    input  wire M_AXI_DRAM_awready,
    output wire [MW-1:0] M_AXI_DRAM_wdata,
    output wire [MW/8-1:0] M_AXI_DRAM_wstrb,
    output wire M_AXI_DRAM_wlast,
    output wire M_AXI_DRAM_wvalid,
    input  wire M_AXI_DRAM_wready,
    input  wire [IDW-1:0] M_AXI_DRAM_bid,
    input  wire [2-1:0] M_AXI_DRAM_bresp,
    input  wire M_AXI_DRAM_bvalid,
    output wire M_AXI_DRAM_bready,
    output wire [IDW-1:0] M_AXI_DRAM_arid,
    output wire [AW-1:0] M_AXI_DRAM_araddr,
    output wire [8-1:0] M_AXI_DRAM_arlen,
    output wire [3-1:0] M_AXI_DRAM_arsize,
    output wire [2-1:0] M_AXI_DRAM_arburst,
    output wire M_AXI_DRAM_arvalid,
    input  wire M_AXI_DRAM_arready,
    input  wire [IDW-1:0] M_AXI_DRAM_rid,
    input  wire [MW-1:0] M_AXI_DRAM_rdata,
    input  wire [2-1:0] M_AXI_DRAM_rresp,
    input  wire M_AXI_DRAM_rlast,
    input  wire M_AXI_DRAM_rvalid,
    output wire M_AXI_DRAM_rready,
    // ---- M_AXIS_LINK0 / S_AXIS_LINK0 ----
    output wire [LKW-1:0] M_AXIS_LINK0_tdata,
    input  wire [LKW-1:0] S_AXIS_LINK0_tdata,
    output wire [LKU-1:0] M_AXIS_LINK0_tuser,
    input  wire [LKU-1:0] S_AXIS_LINK0_tuser,
    output wire M_AXIS_LINK0_tlast,
    input  wire S_AXIS_LINK0_tlast,
    output wire M_AXIS_LINK0_tvalid,
    input  wire S_AXIS_LINK0_tvalid,
    input  wire M_AXIS_LINK0_tready,
    output wire S_AXIS_LINK0_tready,
    // ---- M_AXIS_LINK1 / S_AXIS_LINK1 ----
    output wire [LKW-1:0] M_AXIS_LINK1_tdata,
    input  wire [LKW-1:0] S_AXIS_LINK1_tdata,
    output wire [LKU-1:0] M_AXIS_LINK1_tuser,
    input  wire [LKU-1:0] S_AXIS_LINK1_tuser,
    output wire M_AXIS_LINK1_tlast,
    input  wire S_AXIS_LINK1_tlast,
    output wire M_AXIS_LINK1_tvalid,
    input  wire S_AXIS_LINK1_tvalid,
    input  wire M_AXIS_LINK1_tready,
    output wire S_AXIS_LINK1_tready
);
    localparam integer NMAG = 2;
    localparam integer NCU  = 6;
    localparam integer NVEC = 2;

    // The instances below are written against clk/resetn; aliasing once here
    // keeps the generator's body independent of the boundary's naming.
    wire clk    = axi_aclk;
    wire resetn = axi_aresetn;
    wire rst    = !resetn;





    wire [NMAG*FW-1:0] mag_o_d;
    wire [NMAG-1:0]    mag_i_v, mag_i_b, mag_o_v, mag_o_b;
    wire [15:0]        mag_rd, mag_wr;

    wire [15:0] cu_f [0:NCU-1];
    wire [15:0] cu_g [0:NCU-1];
    wire [15:0] cu_d [0:NCU-1];
    wire [31:0] vc_cyc [0:NVEC-1];
    wire        vc_flt [0:NVEC-1];

    // The mover is commanded through S_AXI_CTRL, so its status is internal and
    // reaches `obs` only to stop synthesis pruning it.
    wire        mv_busy;
    wire [3:0]  mv_fault;
    wire [31:0] mv_done;

    wire [FW-1:0] l000_h0_1_fd; wire l000_h0_1_fv; wire l000_h0_1_fb;
    wire [FW-1:0] l000_h0_1_rd; wire l000_h0_1_rv; wire l000_h0_1_rb;
    wire [FW-1:0] l001_h1_1_fd; wire l001_h1_1_fv; wire l001_h1_1_fb;
    wire [FW-1:0] l001_h1_1_rd; wire l001_h1_1_rv; wire l001_h1_1_rb;
    wire [FW-1:0] l002_v1_0_fd; wire l002_v1_0_fv; wire l002_v1_0_fb;
    wire [FW-1:0] l002_v1_0_rd; wire l002_v1_0_rv; wire l002_v1_0_rb;
    wire [FW-1:0] l003_v1_1_fd; wire l003_v1_1_fv; wire l003_v1_1_fb;
    wire [FW-1:0] l003_v1_1_rd; wire l003_v1_1_rv; wire l003_v1_1_rb;
    wire [FW-1:0] l004_L1_1_fd; wire l004_L1_1_fv; wire l004_L1_1_fb;
    wire [FW-1:0] l004_L1_1_rd; wire l004_L1_1_rv; wire l004_L1_1_rb;
    wire [FW-1:0] l005_h2_1_fd; wire l005_h2_1_fv; wire l005_h2_1_fb;
    wire [FW-1:0] l005_h2_1_rd; wire l005_h2_1_rv; wire l005_h2_1_rb;
    wire [FW-1:0] l006_v2_0_fd; wire l006_v2_0_fv; wire l006_v2_0_fb;
    wire [FW-1:0] l006_v2_0_rd; wire l006_v2_0_rv; wire l006_v2_0_rb;
    wire [FW-1:0] l007_v2_1_fd; wire l007_v2_1_fv; wire l007_v2_1_fb;
    wire [FW-1:0] l007_v2_1_rd; wire l007_v2_1_rv; wire l007_v2_1_rb;
    wire [FW-1:0] l008_L2_1_fd; wire l008_L2_1_fv; wire l008_L2_1_fb;
    wire [FW-1:0] l008_L2_1_rd; wire l008_L2_1_rv; wire l008_L2_1_rb;
    wire [FW-1:0] l009_h0_2_fd; wire l009_h0_2_fv; wire l009_h0_2_fb;
    wire [FW-1:0] l009_h0_2_rd; wire l009_h0_2_rv; wire l009_h0_2_rb;
    wire [FW-1:0] l010_h1_2_fd; wire l010_h1_2_fv; wire l010_h1_2_fb;
    wire [FW-1:0] l010_h1_2_rd; wire l010_h1_2_rv; wire l010_h1_2_rb;
    wire [FW-1:0] l011_v1_2_fd; wire l011_v1_2_fv; wire l011_v1_2_fb;
    wire [FW-1:0] l011_v1_2_rd; wire l011_v1_2_rv; wire l011_v1_2_rb;
    wire [FW-1:0] l012_L1_2_fd; wire l012_L1_2_fv; wire l012_L1_2_fb;
    wire [FW-1:0] l012_L1_2_rd; wire l012_L1_2_rv; wire l012_L1_2_rb;
    wire [FW-1:0] l013_h2_2_fd; wire l013_h2_2_fv; wire l013_h2_2_fb;
    wire [FW-1:0] l013_h2_2_rd; wire l013_h2_2_rv; wire l013_h2_2_rb;
    wire [FW-1:0] l014_v2_2_fd; wire l014_v2_2_fv; wire l014_v2_2_fb;
    wire [FW-1:0] l014_v2_2_rd; wire l014_v2_2_rv; wire l014_v2_2_rb;
    wire [FW-1:0] l015_L2_2_fd; wire l015_L2_2_fv; wire l015_L2_2_fb;
    wire [FW-1:0] l015_L2_2_rd; wire l015_L2_2_rv; wire l015_L2_2_rb;

    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(1), .POS_Y(1), .GRID_LO(1),
                .GRID_HI(2), .GRID_X_HI(2),
                .GRID_Y_HI(2)) r1_1 (
        .clk(clk), .rst(rst),
        .west_in_data(l000_h0_1_fd),   .west_in_valid(l000_h0_1_fv),   .west_in_busy(l000_h0_1_fb),
        .west_out_data(l000_h0_1_rd),  .west_out_valid(l000_h0_1_rv),  .west_out_busy(l000_h0_1_rb),
        .east_in_data(l001_h1_1_rd),   .east_in_valid(l001_h1_1_rv),   .east_in_busy(l001_h1_1_rb),
        .east_out_data(l001_h1_1_fd),  .east_out_valid(l001_h1_1_fv),  .east_out_busy(l001_h1_1_fb),
        .north_in_data(l002_v1_0_fd),  .north_in_valid(l002_v1_0_fv),  .north_in_busy(l002_v1_0_fb),
        .north_out_data(l002_v1_0_rd), .north_out_valid(l002_v1_0_rv), .north_out_busy(l002_v1_0_rb),
        .south_in_data(l003_v1_1_rd),  .south_in_valid(l003_v1_1_rv),  .south_in_busy(l003_v1_1_rb),
        .south_out_data(l003_v1_1_fd), .south_out_valid(l003_v1_1_fv), .south_out_busy(l003_v1_1_fb),
        .local_in_data(l004_L1_1_fd),  .local_in_valid(l004_L1_1_fv),  .local_in_busy(l004_L1_1_fb),
        .local_out_data(l004_L1_1_rd), .local_out_valid(l004_L1_1_rv), .local_out_busy(l004_L1_1_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(2), .POS_Y(1), .GRID_LO(1),
                .GRID_HI(2), .GRID_X_HI(2),
                .GRID_Y_HI(2)) r2_1 (
        .clk(clk), .rst(rst),
        .west_in_data(l001_h1_1_fd),   .west_in_valid(l001_h1_1_fv),   .west_in_busy(l001_h1_1_fb),
        .west_out_data(l001_h1_1_rd),  .west_out_valid(l001_h1_1_rv),  .west_out_busy(l001_h1_1_rb),
        .east_in_data(l005_h2_1_rd),   .east_in_valid(l005_h2_1_rv),   .east_in_busy(l005_h2_1_rb),
        .east_out_data(l005_h2_1_fd),  .east_out_valid(l005_h2_1_fv),  .east_out_busy(l005_h2_1_fb),
        .north_in_data(l006_v2_0_fd),  .north_in_valid(l006_v2_0_fv),  .north_in_busy(l006_v2_0_fb),
        .north_out_data(l006_v2_0_rd), .north_out_valid(l006_v2_0_rv), .north_out_busy(l006_v2_0_rb),
        .south_in_data(l007_v2_1_rd),  .south_in_valid(l007_v2_1_rv),  .south_in_busy(l007_v2_1_rb),
        .south_out_data(l007_v2_1_fd), .south_out_valid(l007_v2_1_fv), .south_out_busy(l007_v2_1_fb),
        .local_in_data(l008_L2_1_fd),  .local_in_valid(l008_L2_1_fv),  .local_in_busy(l008_L2_1_fb),
        .local_out_data(l008_L2_1_rd), .local_out_valid(l008_L2_1_rv), .local_out_busy(l008_L2_1_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(1), .POS_Y(2), .GRID_LO(1),
                .GRID_HI(2), .GRID_X_HI(2),
                .GRID_Y_HI(2)) r1_2 (
        .clk(clk), .rst(rst),
        .west_in_data(l009_h0_2_fd),   .west_in_valid(l009_h0_2_fv),   .west_in_busy(l009_h0_2_fb),
        .west_out_data(l009_h0_2_rd),  .west_out_valid(l009_h0_2_rv),  .west_out_busy(l009_h0_2_rb),
        .east_in_data(l010_h1_2_rd),   .east_in_valid(l010_h1_2_rv),   .east_in_busy(l010_h1_2_rb),
        .east_out_data(l010_h1_2_fd),  .east_out_valid(l010_h1_2_fv),  .east_out_busy(l010_h1_2_fb),
        .north_in_data(l003_v1_1_fd),  .north_in_valid(l003_v1_1_fv),  .north_in_busy(l003_v1_1_fb),
        .north_out_data(l003_v1_1_rd), .north_out_valid(l003_v1_1_rv), .north_out_busy(l003_v1_1_rb),
        .south_in_data(l011_v1_2_rd),  .south_in_valid(l011_v1_2_rv),  .south_in_busy(l011_v1_2_rb),
        .south_out_data(l011_v1_2_fd), .south_out_valid(l011_v1_2_fv), .south_out_busy(l011_v1_2_fb),
        .local_in_data(l012_L1_2_fd),  .local_in_valid(l012_L1_2_fv),  .local_in_busy(l012_L1_2_fb),
        .local_out_data(l012_L1_2_rd), .local_out_valid(l012_L1_2_rv), .local_out_busy(l012_L1_2_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(2), .POS_Y(2), .GRID_LO(1),
                .GRID_HI(2), .GRID_X_HI(2),
                .GRID_Y_HI(2)) r2_2 (
        .clk(clk), .rst(rst),
        .west_in_data(l010_h1_2_fd),   .west_in_valid(l010_h1_2_fv),   .west_in_busy(l010_h1_2_fb),
        .west_out_data(l010_h1_2_rd),  .west_out_valid(l010_h1_2_rv),  .west_out_busy(l010_h1_2_rb),
        .east_in_data(l013_h2_2_rd),   .east_in_valid(l013_h2_2_rv),   .east_in_busy(l013_h2_2_rb),
        .east_out_data(l013_h2_2_fd),  .east_out_valid(l013_h2_2_fv),  .east_out_busy(l013_h2_2_fb),
        .north_in_data(l007_v2_1_fd),  .north_in_valid(l007_v2_1_fv),  .north_in_busy(l007_v2_1_fb),
        .north_out_data(l007_v2_1_rd), .north_out_valid(l007_v2_1_rv), .north_out_busy(l007_v2_1_rb),
        .south_in_data(l014_v2_2_rd),  .south_in_valid(l014_v2_2_rv),  .south_in_busy(l014_v2_2_rb),
        .south_out_data(l014_v2_2_fd), .south_out_valid(l014_v2_2_fv), .south_out_busy(l014_v2_2_fb),
        .local_in_data(l015_L2_2_fd),  .local_in_valid(l015_L2_2_fv),  .local_in_busy(l015_L2_2_fb),
        .local_out_data(l015_L2_2_rd), .local_out_valid(l015_L2_2_rv), .local_out_busy(l015_L2_2_rb)
    );
    assign l000_h0_1_fv = mag_o_v[0];
    assign mag_o_b[0] = l000_h0_1_fb;
    assign mag_i_v[0] = l000_h0_1_rv;
    assign l000_h0_1_rb = mag_i_b[0];
    assign l009_h0_2_fv = mag_o_v[1];
    assign mag_o_b[1] = l009_h0_2_fb;
    assign mag_i_v[1] = l009_h0_2_rv;
    assign l009_h0_2_rb = mag_i_b[1];
    assign l000_h0_1_fd = mag_o_d[0*FW +: FW];
    assign l009_h0_2_fd = mag_o_d[1*FW +: FW];
    mag_1m #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .DATA_W(DW), .ADDR_W(AW),
          .ID_W(IDW), .MEM_PORTS(2), .MEM_X(0), .MEM_Y(1), .MEM_X1(0), .MEM_Y1(2),
          .GRID_LO(1), .GRID_HI(2), .STAGE_FLITS(128),
          .ILINK(1), .MESH_ID(MESH_ID), .LINK_W(LKW), .TUSER_W(LKU),
          .MW(MW)) u_mag (
        .clk(clk), .resetn(resetn),
        .dram_aclk(dram_aclk), .dram_aresetn(dram_aresetn),
        .sm_awid(S_AXI_MEM_awid), .sm_awaddr(S_AXI_MEM_awaddr),
        .sm_awlen(S_AXI_MEM_awlen), .sm_awvalid(S_AXI_MEM_awvalid),
        .sm_awready(S_AXI_MEM_awready),
        .sm_wdata(S_AXI_MEM_wdata), .sm_wstrb(S_AXI_MEM_wstrb),
        .sm_wlast(S_AXI_MEM_wlast), .sm_wvalid(S_AXI_MEM_wvalid),
        .sm_wready(S_AXI_MEM_wready),
        .sm_bid(S_AXI_MEM_bid), .sm_bresp(S_AXI_MEM_bresp),
        .sm_bvalid(S_AXI_MEM_bvalid), .sm_bready(S_AXI_MEM_bready),
        .sm_arid(S_AXI_MEM_arid), .sm_araddr(S_AXI_MEM_araddr),
        .sm_arlen(S_AXI_MEM_arlen), .sm_arvalid(S_AXI_MEM_arvalid),
        .sm_arready(S_AXI_MEM_arready),
        .sm_rid(S_AXI_MEM_rid), .sm_rdata(S_AXI_MEM_rdata),
        .sm_rresp(S_AXI_MEM_rresp), .sm_rlast(S_AXI_MEM_rlast),
        .sm_rvalid(S_AXI_MEM_rvalid), .sm_rready(S_AXI_MEM_rready),
        .sc_awid(S_AXI_CTRL_awid), .sc_awaddr(S_AXI_CTRL_awaddr),
        .sc_awlen(S_AXI_CTRL_awlen), .sc_awvalid(S_AXI_CTRL_awvalid),
        .sc_awready(S_AXI_CTRL_awready),
        .sc_wdata(S_AXI_CTRL_wdata), .sc_wstrb(S_AXI_CTRL_wstrb),
        .sc_wlast(S_AXI_CTRL_wlast), .sc_wvalid(S_AXI_CTRL_wvalid),
        .sc_wready(S_AXI_CTRL_wready),
        .sc_bid(S_AXI_CTRL_bid), .sc_bresp(S_AXI_CTRL_bresp),
        .sc_bvalid(S_AXI_CTRL_bvalid), .sc_bready(S_AXI_CTRL_bready),
        .sc_arid(S_AXI_CTRL_arid), .sc_araddr(S_AXI_CTRL_araddr),
        .sc_arlen(S_AXI_CTRL_arlen), .sc_arvalid(S_AXI_CTRL_arvalid),
        .sc_arready(S_AXI_CTRL_arready),
        .sc_rid(S_AXI_CTRL_rid), .sc_rdata(S_AXI_CTRL_rdata),
        .sc_rresp(S_AXI_CTRL_rresp), .sc_rlast(S_AXI_CTRL_rlast),
        .sc_rvalid(S_AXI_CTRL_rvalid), .sc_rready(S_AXI_CTRL_rready),
        .m_awid(M_AXI_DRAM_awid),
        .m_awaddr(M_AXI_DRAM_awaddr),
        .m_awlen(M_AXI_DRAM_awlen),
        .m_awsize(M_AXI_DRAM_awsize),
        .m_awburst(M_AXI_DRAM_awburst),
        .m_awvalid(M_AXI_DRAM_awvalid),
        .m_awready(M_AXI_DRAM_awready),
        .m_wdata(M_AXI_DRAM_wdata),
        .m_wstrb(M_AXI_DRAM_wstrb),
        .m_wlast(M_AXI_DRAM_wlast),
        .m_wvalid(M_AXI_DRAM_wvalid),
        .m_wready(M_AXI_DRAM_wready),
        .m_bid(M_AXI_DRAM_bid),
        .m_bresp(M_AXI_DRAM_bresp),
        .m_bvalid(M_AXI_DRAM_bvalid),
        .m_bready(M_AXI_DRAM_bready),
        .m_arid(M_AXI_DRAM_arid),
        .m_araddr(M_AXI_DRAM_araddr),
        .m_arlen(M_AXI_DRAM_arlen),
        .m_arsize(M_AXI_DRAM_arsize),
        .m_arburst(M_AXI_DRAM_arburst),
        .m_arvalid(M_AXI_DRAM_arvalid),
        .m_arready(M_AXI_DRAM_arready),
        .m_rid(M_AXI_DRAM_rid),
        .m_rdata(M_AXI_DRAM_rdata),
        .m_rresp(M_AXI_DRAM_rresp),
        .m_rlast(M_AXI_DRAM_rlast),
        .m_rvalid(M_AXI_DRAM_rvalid),
        .m_rready(M_AXI_DRAM_rready),
        .link0_out_tdata(M_AXIS_LINK0_tdata), .link0_out_tuser(M_AXIS_LINK0_tuser),
        .link0_out_tlast(M_AXIS_LINK0_tlast), .link0_out_tvalid(M_AXIS_LINK0_tvalid),
        .link0_out_tready(M_AXIS_LINK0_tready),
        .link0_in_tdata(S_AXIS_LINK0_tdata), .link0_in_tuser(S_AXIS_LINK0_tuser),
        .link0_in_tlast(S_AXIS_LINK0_tlast), .link0_in_tvalid(S_AXIS_LINK0_tvalid),
        .link0_in_tready(S_AXIS_LINK0_tready),
        .link1_out_tdata(M_AXIS_LINK1_tdata), .link1_out_tuser(M_AXIS_LINK1_tuser),
        .link1_out_tlast(M_AXIS_LINK1_tlast), .link1_out_tvalid(M_AXIS_LINK1_tvalid),
        .link1_out_tready(M_AXIS_LINK1_tready),
        .link1_in_tdata(S_AXIS_LINK1_tdata), .link1_in_tuser(S_AXIS_LINK1_tuser),
        .link1_in_tlast(S_AXIS_LINK1_tlast), .link1_in_tvalid(S_AXIS_LINK1_tvalid),
        .link1_in_tready(S_AXIS_LINK1_tready),
        .mem_in_data({l009_h0_2_rd, l000_h0_1_rd}), .mem_in_valid(mag_i_v), .mem_in_busy(mag_i_b),
        .mem_out_data(mag_o_d), .mem_out_valid(mag_o_v), .mem_out_busy(mag_o_b),
        .mem_rd_count(mag_rd), .mem_wr_count(mag_wr),
        .mv_busy(mv_busy), .mv_fault(mv_fault), .mv_done(mv_done)
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(0), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM), .TILE_PRIM(TILE_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(1), .MODEL(MODEL)) u_cu0 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l002_v1_0_fd), .noc_out_valid(l002_v1_0_fv), .noc_out_busy(l002_v1_0_fb), .noc_in_data(l002_v1_0_rd), .noc_in_valid(l002_v1_0_rv), .noc_in_busy(l002_v1_0_rb),
        .fills_done(cu_f[0]), .gemms_done(cu_g[0]), .drains_done(cu_d[0])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(1), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM), .TILE_PRIM(TILE_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(1), .MODEL(MODEL)) u_cu1 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l004_L1_1_fd), .noc_out_valid(l004_L1_1_fv), .noc_out_busy(l004_L1_1_fb), .noc_in_data(l004_L1_1_rd), .noc_in_valid(l004_L1_1_rv), .noc_in_busy(l004_L1_1_rb),
        .fills_done(cu_f[1]), .gemms_done(cu_g[1]), .drains_done(cu_d[1])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(2), .CU_Y(1), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM), .TILE_PRIM(TILE_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(1), .MODEL(MODEL)) u_cu2 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l008_L2_1_fd), .noc_out_valid(l008_L2_1_fv), .noc_out_busy(l008_L2_1_fb), .noc_in_data(l008_L2_1_rd), .noc_in_valid(l008_L2_1_rv), .noc_in_busy(l008_L2_1_rb),
        .fills_done(cu_f[2]), .gemms_done(cu_g[2]), .drains_done(cu_d[2])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(2), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM), .TILE_PRIM(TILE_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(2), .MODEL(MODEL)) u_cu3 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l012_L1_2_fd), .noc_out_valid(l012_L1_2_fv), .noc_out_busy(l012_L1_2_fb), .noc_in_data(l012_L1_2_rd), .noc_in_valid(l012_L1_2_rv), .noc_in_busy(l012_L1_2_rb),
        .fills_done(cu_f[3]), .gemms_done(cu_g[3]), .drains_done(cu_d[3])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(2), .CU_Y(2), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM), .TILE_PRIM(TILE_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(2), .MODEL(MODEL)) u_cu4 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l015_L2_2_fd), .noc_out_valid(l015_L2_2_fv), .noc_out_busy(l015_L2_2_fb), .noc_in_data(l015_L2_2_rd), .noc_in_valid(l015_L2_2_rv), .noc_in_busy(l015_L2_2_rb),
        .fills_done(cu_f[4]), .gemms_done(cu_g[4]), .drains_done(cu_d[4])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(3), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM), .TILE_PRIM(TILE_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(2), .MODEL(MODEL)) u_cu5 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l011_v1_2_rd), .noc_out_valid(l011_v1_2_rv), .noc_out_busy(l011_v1_2_rb), .noc_in_data(l011_v1_2_fd), .noc_in_valid(l011_v1_2_fv), .noc_in_busy(l011_v1_2_fb),
        .fills_done(cu_f[5]), .gemms_done(cu_g[5]), .drains_done(cu_d[5])
    );
    vec_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .POS_X(2), .POS_Y(0),
             .MEM_X(0), .MEM_Y(1), .MODEL(MODEL),
             .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
             .L1_DEPTH(L1_DEPTH), .L1_PRIM(VEC_PRIM)) u_vec0 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l006_v2_0_fd), .noc_out_valid(l006_v2_0_fv), .noc_out_busy(l006_v2_0_fb), .noc_in_data(l006_v2_0_rd), .noc_in_valid(l006_v2_0_rv), .noc_in_busy(l006_v2_0_rb),
        .dbg_cycles(vc_cyc[0]), .dbg_fault(vc_flt[0])
    );
    vec_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .POS_X(2), .POS_Y(3),
             .MEM_X(0), .MEM_Y(2), .MODEL(MODEL),
             .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
             .L1_DEPTH(L1_DEPTH), .L1_PRIM(VEC_PRIM)) u_vec1 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l014_v2_2_rd), .noc_out_valid(l014_v2_2_rv), .noc_out_busy(l014_v2_2_rb), .noc_in_data(l014_v2_2_fd), .noc_in_valid(l014_v2_2_fv), .noc_in_busy(l014_v2_2_fb),
        .dbg_cycles(vc_cyc[1]), .dbg_fault(vc_flt[1])
    );
    assign l005_h2_1_rd = {FW{1'b0}}; assign l005_h2_1_rv = 1'b0; assign l005_h2_1_fb = 1'b0;
    assign l013_h2_2_rd = {FW{1'b0}}; assign l013_h2_2_rv = 1'b0; assign l013_h2_2_fb = 1'b0;

    // The boundary is clock, reset and AXI. There is deliberately no `obs`
    // fold: it existed to stop synthesis pruning these counters, which no
    // software can read, so it was keeping dead logic alive and inflating
    // every measurement taken through it. Pruning them is the right answer.

endmodule

`default_nettype wire
