// ktpu_ship_3x2_il -- GENERATED by scripts/py/gen_mesh.py. Do not edit by hand.
//
//   xxx vec vec xxx
//   mag mat mat nul
//   mag mat mat nul
//   mag mat mat nul
//   xxx vec vec xxx
//
// 2x3 routers, 3 MAG port(s), 6 cluster(s), 4 vector core(s).
// GRID_X_HI=2 GRID_Y_HI=3: the clamp is per axis, so the grid need not
// be square. Edge endpoints live outside the router grid and are reached by it.
//
// MAG presents MEM_PORTS+3 = 6 AXI masters -- one per memory port, plus the
// host upload and the memory mover, plus the interlink's landing channel. Merge them with one SmartConnect in the
// block design; hand-written arbitration here would duplicate it badly.
//
// INTERLINK ON. Two full-duplex links: M_AXIS_LINKn out, S_AXIS_LINKn in.
// link0 flips the mesh's x, link1 flips its y (mag_switch.v).
// TREADY MUST NOT CROSS AN SLR. The far end has to be another mesh's
// S_AXIS_LINK, whose tready is tied high; a real slave there reintroduces the
// combinational SLR crossing mag_link.v exists to avoid.

`default_nettype none

module ktpu_ship_3x2_il #(
    parameter integer FW       = 288,
    parameter integer PW       = 4,
    parameter integer DW       = 256,
    parameter integer AW       = 34,
    parameter integer IDW      = 4,
    parameter integer NM       = 6,
    // One flit per beat at 288, so a packet's framing is its own length; 96
    // is mag.v's TUSER_W.
    parameter integer LKW      = 288,
    parameter integer LKU      = 96,
    // Only the RESET value -- IL_MESH is writable, so the four instances of
    // this module differ by this parameter alone.
    parameter integer MESH_ID  = 0,
    parameter integer MODEL    = 0,
    parameter integer L1_DEPTH = 512,
    // src/ktpu/hw/bench.py's TILES / L1_A_ENTRIES / L1_B_ENTRIES. A generated
    // top that omits them elaborates mx_cluster_cu's 256/32/32 instead.
    parameter integer TILES    = 512,
    // 512/512, NOT the compiler's 128/256: capacity is an upper bound the
    // planner need not fill, and at 928 bits wide the BRAM cost is set by
    // WIDTH -- 13 RAMB36 per port at any depth to 512 -- so the extra is free.
    // 512 needs the L1 BANK BIT, because aoff/boff are 8-bit fields: the
    // address is the bank concatenated with the offset, and the bank is
    // CU_INST [114]/[113]/[112] -- docs/isa/cluster.md s4.6. Two banks is the
    // ceiling; deeper needs a second bit, which mx_cluster_mgr reports.
    parameter integer GA       = 512,
    parameter integer GB       = 512,
    // MUST be "block" at these depths: 512 x 928 bits of LUTRAM per port is
    // ~100k LUT per cluster. The two parameters are not independent.
    parameter         L1_PRIM  = "block",
    // 512 BECAUSE THE DEPTH IS ALREADY PAID FOR. A 288-bit FIFO is 4 RAMB36 at
    // any depth to 512, so the old 32/64 used 6%/12% of their own tiles.
    // Measured on noc_cu_base: 8 BRAM either way, +34 LUT, 574 -> 567 MHz.
    parameter integer INST_DEPTH = 512,
    parameter integer RECV_DEPTH = 512
)(
    // One clock and one reset for every interface, master and slave alike, so
    // neither carries an s_ or m_ prefix. ASSOCIATED_BUSIF names them all, which
    // is what makes the block design tie them up on its own.
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 axi_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S_AXI_MEM:S_AXI_CTRL:M_AXI_MEM0:M_AXI_MEM1:M_AXI_MEM2:M_AXI_UPLOAD:M_AXI_MOVER:M_AXI_ILINK:M_AXIS_LINK0:S_AXIS_LINK0:M_AXIS_LINK1:S_AXIS_LINK1, ASSOCIATED_RESET axi_aresetn" *)
    input  wire axi_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 axi_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire axi_aresetn,

    input  wire [IDW-1:0]   S_AXI_MEM_awid,
    input  wire [AW-1:0]    S_AXI_MEM_awaddr,
    input  wire [7:0]       S_AXI_MEM_awlen,
    input  wire             S_AXI_MEM_awvalid,
    output wire             S_AXI_MEM_awready,
    input  wire [DW-1:0]    S_AXI_MEM_wdata,
    input  wire [DW/8-1:0]  S_AXI_MEM_wstrb,
    input  wire             S_AXI_MEM_wlast,
    input  wire             S_AXI_MEM_wvalid,
    output wire             S_AXI_MEM_wready,
    output wire [IDW-1:0]   S_AXI_MEM_bid,
    output wire [1:0]       S_AXI_MEM_bresp,
    output wire             S_AXI_MEM_bvalid,
    input  wire             S_AXI_MEM_bready,
    input  wire [IDW-1:0]   S_AXI_MEM_arid,
    input  wire [AW-1:0]    S_AXI_MEM_araddr,
    input  wire [7:0]       S_AXI_MEM_arlen,
    input  wire             S_AXI_MEM_arvalid,
    output wire             S_AXI_MEM_arready,
    output wire [IDW-1:0]   S_AXI_MEM_rid,
    output wire [DW-1:0]    S_AXI_MEM_rdata,
    output wire [1:0]       S_AXI_MEM_rresp,
    output wire             S_AXI_MEM_rlast,
    output wire             S_AXI_MEM_rvalid,
    input  wire             S_AXI_MEM_rready,

    input  wire [IDW-1:0]   S_AXI_CTRL_awid,
    input  wire [31:0]      S_AXI_CTRL_awaddr,
    input  wire [7:0]       S_AXI_CTRL_awlen,
    input  wire             S_AXI_CTRL_awvalid,
    output wire             S_AXI_CTRL_awready,
    input  wire [63:0]      S_AXI_CTRL_wdata,
    input  wire [7:0]       S_AXI_CTRL_wstrb,
    input  wire             S_AXI_CTRL_wlast,
    input  wire             S_AXI_CTRL_wvalid,
    output wire             S_AXI_CTRL_wready,
    output wire [IDW-1:0]   S_AXI_CTRL_bid,
    output wire [1:0]       S_AXI_CTRL_bresp,
    output wire             S_AXI_CTRL_bvalid,
    input  wire             S_AXI_CTRL_bready,
    input  wire [IDW-1:0]   S_AXI_CTRL_arid,
    input  wire [31:0]      S_AXI_CTRL_araddr,
    input  wire [7:0]       S_AXI_CTRL_arlen,
    input  wire             S_AXI_CTRL_arvalid,
    output wire             S_AXI_CTRL_arready,
    output wire [IDW-1:0]   S_AXI_CTRL_rid,
    output wire [63:0]      S_AXI_CTRL_rdata,
    output wire [1:0]       S_AXI_CTRL_rresp,
    output wire             S_AXI_CTRL_rlast,
    output wire             S_AXI_CTRL_rvalid,
    input  wire             S_AXI_CTRL_rready,

    // ---- M_AXI_MEM0 ----
    output wire [IDW-1:0] M_AXI_MEM0_awid,
    output wire [AW-1:0] M_AXI_MEM0_awaddr,
    output wire [8-1:0] M_AXI_MEM0_awlen,
    output wire [3-1:0] M_AXI_MEM0_awsize,
    output wire [2-1:0] M_AXI_MEM0_awburst,
    output wire M_AXI_MEM0_awvalid,
    input  wire M_AXI_MEM0_awready,
    output wire [DW-1:0] M_AXI_MEM0_wdata,
    output wire [DW/8-1:0] M_AXI_MEM0_wstrb,
    output wire M_AXI_MEM0_wlast,
    output wire M_AXI_MEM0_wvalid,
    input  wire M_AXI_MEM0_wready,
    input  wire [IDW-1:0] M_AXI_MEM0_bid,
    input  wire [2-1:0] M_AXI_MEM0_bresp,
    input  wire M_AXI_MEM0_bvalid,
    output wire M_AXI_MEM0_bready,
    output wire [IDW-1:0] M_AXI_MEM0_arid,
    output wire [AW-1:0] M_AXI_MEM0_araddr,
    output wire [8-1:0] M_AXI_MEM0_arlen,
    output wire [3-1:0] M_AXI_MEM0_arsize,
    output wire [2-1:0] M_AXI_MEM0_arburst,
    output wire M_AXI_MEM0_arvalid,
    input  wire M_AXI_MEM0_arready,
    input  wire [IDW-1:0] M_AXI_MEM0_rid,
    input  wire [DW-1:0] M_AXI_MEM0_rdata,
    input  wire [2-1:0] M_AXI_MEM0_rresp,
    input  wire M_AXI_MEM0_rlast,
    input  wire M_AXI_MEM0_rvalid,
    output wire M_AXI_MEM0_rready,
    // ---- M_AXI_MEM1 ----
    output wire [IDW-1:0] M_AXI_MEM1_awid,
    output wire [AW-1:0] M_AXI_MEM1_awaddr,
    output wire [8-1:0] M_AXI_MEM1_awlen,
    output wire [3-1:0] M_AXI_MEM1_awsize,
    output wire [2-1:0] M_AXI_MEM1_awburst,
    output wire M_AXI_MEM1_awvalid,
    input  wire M_AXI_MEM1_awready,
    output wire [DW-1:0] M_AXI_MEM1_wdata,
    output wire [DW/8-1:0] M_AXI_MEM1_wstrb,
    output wire M_AXI_MEM1_wlast,
    output wire M_AXI_MEM1_wvalid,
    input  wire M_AXI_MEM1_wready,
    input  wire [IDW-1:0] M_AXI_MEM1_bid,
    input  wire [2-1:0] M_AXI_MEM1_bresp,
    input  wire M_AXI_MEM1_bvalid,
    output wire M_AXI_MEM1_bready,
    output wire [IDW-1:0] M_AXI_MEM1_arid,
    output wire [AW-1:0] M_AXI_MEM1_araddr,
    output wire [8-1:0] M_AXI_MEM1_arlen,
    output wire [3-1:0] M_AXI_MEM1_arsize,
    output wire [2-1:0] M_AXI_MEM1_arburst,
    output wire M_AXI_MEM1_arvalid,
    input  wire M_AXI_MEM1_arready,
    input  wire [IDW-1:0] M_AXI_MEM1_rid,
    input  wire [DW-1:0] M_AXI_MEM1_rdata,
    input  wire [2-1:0] M_AXI_MEM1_rresp,
    input  wire M_AXI_MEM1_rlast,
    input  wire M_AXI_MEM1_rvalid,
    output wire M_AXI_MEM1_rready,
    // ---- M_AXI_MEM2 ----
    output wire [IDW-1:0] M_AXI_MEM2_awid,
    output wire [AW-1:0] M_AXI_MEM2_awaddr,
    output wire [8-1:0] M_AXI_MEM2_awlen,
    output wire [3-1:0] M_AXI_MEM2_awsize,
    output wire [2-1:0] M_AXI_MEM2_awburst,
    output wire M_AXI_MEM2_awvalid,
    input  wire M_AXI_MEM2_awready,
    output wire [DW-1:0] M_AXI_MEM2_wdata,
    output wire [DW/8-1:0] M_AXI_MEM2_wstrb,
    output wire M_AXI_MEM2_wlast,
    output wire M_AXI_MEM2_wvalid,
    input  wire M_AXI_MEM2_wready,
    input  wire [IDW-1:0] M_AXI_MEM2_bid,
    input  wire [2-1:0] M_AXI_MEM2_bresp,
    input  wire M_AXI_MEM2_bvalid,
    output wire M_AXI_MEM2_bready,
    output wire [IDW-1:0] M_AXI_MEM2_arid,
    output wire [AW-1:0] M_AXI_MEM2_araddr,
    output wire [8-1:0] M_AXI_MEM2_arlen,
    output wire [3-1:0] M_AXI_MEM2_arsize,
    output wire [2-1:0] M_AXI_MEM2_arburst,
    output wire M_AXI_MEM2_arvalid,
    input  wire M_AXI_MEM2_arready,
    input  wire [IDW-1:0] M_AXI_MEM2_rid,
    input  wire [DW-1:0] M_AXI_MEM2_rdata,
    input  wire [2-1:0] M_AXI_MEM2_rresp,
    input  wire M_AXI_MEM2_rlast,
    input  wire M_AXI_MEM2_rvalid,
    output wire M_AXI_MEM2_rready,
    // ---- M_AXI_UPLOAD ----
    output wire [IDW-1:0] M_AXI_UPLOAD_awid,
    output wire [AW-1:0] M_AXI_UPLOAD_awaddr,
    output wire [8-1:0] M_AXI_UPLOAD_awlen,
    output wire [3-1:0] M_AXI_UPLOAD_awsize,
    output wire [2-1:0] M_AXI_UPLOAD_awburst,
    output wire M_AXI_UPLOAD_awvalid,
    input  wire M_AXI_UPLOAD_awready,
    output wire [DW-1:0] M_AXI_UPLOAD_wdata,
    output wire [DW/8-1:0] M_AXI_UPLOAD_wstrb,
    output wire M_AXI_UPLOAD_wlast,
    output wire M_AXI_UPLOAD_wvalid,
    input  wire M_AXI_UPLOAD_wready,
    input  wire [IDW-1:0] M_AXI_UPLOAD_bid,
    input  wire [2-1:0] M_AXI_UPLOAD_bresp,
    input  wire M_AXI_UPLOAD_bvalid,
    output wire M_AXI_UPLOAD_bready,
    output wire [IDW-1:0] M_AXI_UPLOAD_arid,
    output wire [AW-1:0] M_AXI_UPLOAD_araddr,
    output wire [8-1:0] M_AXI_UPLOAD_arlen,
    output wire [3-1:0] M_AXI_UPLOAD_arsize,
    output wire [2-1:0] M_AXI_UPLOAD_arburst,
    output wire M_AXI_UPLOAD_arvalid,
    input  wire M_AXI_UPLOAD_arready,
    input  wire [IDW-1:0] M_AXI_UPLOAD_rid,
    input  wire [DW-1:0] M_AXI_UPLOAD_rdata,
    input  wire [2-1:0] M_AXI_UPLOAD_rresp,
    input  wire M_AXI_UPLOAD_rlast,
    input  wire M_AXI_UPLOAD_rvalid,
    output wire M_AXI_UPLOAD_rready,
    // ---- M_AXI_MOVER ----
    output wire [IDW-1:0] M_AXI_MOVER_awid,
    output wire [AW-1:0] M_AXI_MOVER_awaddr,
    output wire [8-1:0] M_AXI_MOVER_awlen,
    output wire [3-1:0] M_AXI_MOVER_awsize,
    output wire [2-1:0] M_AXI_MOVER_awburst,
    output wire M_AXI_MOVER_awvalid,
    input  wire M_AXI_MOVER_awready,
    output wire [DW-1:0] M_AXI_MOVER_wdata,
    output wire [DW/8-1:0] M_AXI_MOVER_wstrb,
    output wire M_AXI_MOVER_wlast,
    output wire M_AXI_MOVER_wvalid,
    input  wire M_AXI_MOVER_wready,
    input  wire [IDW-1:0] M_AXI_MOVER_bid,
    input  wire [2-1:0] M_AXI_MOVER_bresp,
    input  wire M_AXI_MOVER_bvalid,
    output wire M_AXI_MOVER_bready,
    output wire [IDW-1:0] M_AXI_MOVER_arid,
    output wire [AW-1:0] M_AXI_MOVER_araddr,
    output wire [8-1:0] M_AXI_MOVER_arlen,
    output wire [3-1:0] M_AXI_MOVER_arsize,
    output wire [2-1:0] M_AXI_MOVER_arburst,
    output wire M_AXI_MOVER_arvalid,
    input  wire M_AXI_MOVER_arready,
    input  wire [IDW-1:0] M_AXI_MOVER_rid,
    input  wire [DW-1:0] M_AXI_MOVER_rdata,
    input  wire [2-1:0] M_AXI_MOVER_rresp,
    input  wire M_AXI_MOVER_rlast,
    input  wire M_AXI_MOVER_rvalid,
    output wire M_AXI_MOVER_rready,
    // ---- M_AXI_ILINK ----
    output wire [IDW-1:0] M_AXI_ILINK_awid,
    output wire [AW-1:0] M_AXI_ILINK_awaddr,
    output wire [8-1:0] M_AXI_ILINK_awlen,
    output wire [3-1:0] M_AXI_ILINK_awsize,
    output wire [2-1:0] M_AXI_ILINK_awburst,
    output wire M_AXI_ILINK_awvalid,
    input  wire M_AXI_ILINK_awready,
    output wire [DW-1:0] M_AXI_ILINK_wdata,
    output wire [DW/8-1:0] M_AXI_ILINK_wstrb,
    output wire M_AXI_ILINK_wlast,
    output wire M_AXI_ILINK_wvalid,
    input  wire M_AXI_ILINK_wready,
    input  wire [IDW-1:0] M_AXI_ILINK_bid,
    input  wire [2-1:0] M_AXI_ILINK_bresp,
    input  wire M_AXI_ILINK_bvalid,
    output wire M_AXI_ILINK_bready,
    output wire [IDW-1:0] M_AXI_ILINK_arid,
    output wire [AW-1:0] M_AXI_ILINK_araddr,
    output wire [8-1:0] M_AXI_ILINK_arlen,
    output wire [3-1:0] M_AXI_ILINK_arsize,
    output wire [2-1:0] M_AXI_ILINK_arburst,
    output wire M_AXI_ILINK_arvalid,
    input  wire M_AXI_ILINK_arready,
    input  wire [IDW-1:0] M_AXI_ILINK_rid,
    input  wire [DW-1:0] M_AXI_ILINK_rdata,
    input  wire [2-1:0] M_AXI_ILINK_rresp,
    input  wire M_AXI_ILINK_rlast,
    input  wire M_AXI_ILINK_rvalid,
    output wire M_AXI_ILINK_rready,
    // ---- M_AXIS_LINK0 / S_AXIS_LINK0 ----
    output wire [LKW-1:0] M_AXIS_LINK0_tdata,
    input  wire [LKW-1:0] S_AXIS_LINK0_tdata,
    output wire [LKU-1:0] M_AXIS_LINK0_tuser,
    input  wire [LKU-1:0] S_AXIS_LINK0_tuser,
    output wire M_AXIS_LINK0_tlast,
    input  wire S_AXIS_LINK0_tlast,
    output wire M_AXIS_LINK0_tvalid,
    input  wire S_AXIS_LINK0_tvalid,
    input  wire M_AXIS_LINK0_tready,
    output wire S_AXIS_LINK0_tready,
    // ---- M_AXIS_LINK1 / S_AXIS_LINK1 ----
    output wire [LKW-1:0] M_AXIS_LINK1_tdata,
    input  wire [LKW-1:0] S_AXIS_LINK1_tdata,
    output wire [LKU-1:0] M_AXIS_LINK1_tuser,
    input  wire [LKU-1:0] S_AXIS_LINK1_tuser,
    output wire M_AXIS_LINK1_tlast,
    input  wire S_AXIS_LINK1_tlast,
    output wire M_AXIS_LINK1_tvalid,
    input  wire S_AXIS_LINK1_tvalid,
    input  wire M_AXIS_LINK1_tready,
    output wire S_AXIS_LINK1_tready
);
    localparam integer NMAG = 3;
    localparam integer NCU  = 6;
    localparam integer NVEC = 4;

    // The instances below are written against clk/resetn; aliasing once here
    // keeps the generator's body independent of the boundary's naming.
    wire clk    = axi_aclk;
    wire resetn = axi_aresetn;
    wire rst    = !resetn;

    wire [NM*IDW-1:0] mm_awid;
    wire [NM*AW-1:0] mm_awaddr;
    wire [NM*8-1:0] mm_awlen;
    wire [NM*3-1:0] mm_awsize;
    wire [NM*2-1:0] mm_awburst;
    wire [NM-1:0] mm_awvalid;
    wire [NM-1:0] mm_awready;
    wire [NM*DW-1:0] mm_wdata;
    wire [NM*DW/8-1:0] mm_wstrb;
    wire [NM-1:0] mm_wlast;
    wire [NM-1:0] mm_wvalid;
    wire [NM-1:0] mm_wready;
    wire [NM*IDW-1:0] mm_bid;
    wire [NM*2-1:0] mm_bresp;
    wire [NM-1:0] mm_bvalid;
    wire [NM-1:0] mm_bready;
    wire [NM*IDW-1:0] mm_arid;
    wire [NM*AW-1:0] mm_araddr;
    wire [NM*8-1:0] mm_arlen;
    wire [NM*3-1:0] mm_arsize;
    wire [NM*2-1:0] mm_arburst;
    wire [NM-1:0] mm_arvalid;
    wire [NM-1:0] mm_arready;
    wire [NM*IDW-1:0] mm_rid;
    wire [NM*DW-1:0] mm_rdata;
    wire [NM*2-1:0] mm_rresp;
    wire [NM-1:0] mm_rlast;
    wire [NM-1:0] mm_rvalid;
    wire [NM-1:0] mm_rready;

    assign M_AXI_MEM0_awid = mm_awid[0*IDW +: IDW];
    assign M_AXI_MEM0_awaddr = mm_awaddr[0*AW +: AW];
    assign M_AXI_MEM0_awlen = mm_awlen[0*8 +: 8];
    assign M_AXI_MEM0_awsize = mm_awsize[0*3 +: 3];
    assign M_AXI_MEM0_awburst = mm_awburst[0*2 +: 2];
    assign M_AXI_MEM0_awvalid = mm_awvalid[0];
    assign mm_awready[0] = M_AXI_MEM0_awready;
    assign M_AXI_MEM0_wdata = mm_wdata[0*DW +: DW];
    assign M_AXI_MEM0_wstrb = mm_wstrb[0*DW/8 +: DW/8];
    assign M_AXI_MEM0_wlast = mm_wlast[0];
    assign M_AXI_MEM0_wvalid = mm_wvalid[0];
    assign mm_wready[0] = M_AXI_MEM0_wready;
    assign mm_bid[0*IDW +: IDW] = M_AXI_MEM0_bid;
    assign mm_bresp[0*2 +: 2] = M_AXI_MEM0_bresp;
    assign mm_bvalid[0] = M_AXI_MEM0_bvalid;
    assign M_AXI_MEM0_bready = mm_bready[0];
    assign M_AXI_MEM0_arid = mm_arid[0*IDW +: IDW];
    assign M_AXI_MEM0_araddr = mm_araddr[0*AW +: AW];
    assign M_AXI_MEM0_arlen = mm_arlen[0*8 +: 8];
    assign M_AXI_MEM0_arsize = mm_arsize[0*3 +: 3];
    assign M_AXI_MEM0_arburst = mm_arburst[0*2 +: 2];
    assign M_AXI_MEM0_arvalid = mm_arvalid[0];
    assign mm_arready[0] = M_AXI_MEM0_arready;
    assign mm_rid[0*IDW +: IDW] = M_AXI_MEM0_rid;
    assign mm_rdata[0*DW +: DW] = M_AXI_MEM0_rdata;
    assign mm_rresp[0*2 +: 2] = M_AXI_MEM0_rresp;
    assign mm_rlast[0] = M_AXI_MEM0_rlast;
    assign mm_rvalid[0] = M_AXI_MEM0_rvalid;
    assign M_AXI_MEM0_rready = mm_rready[0];
    assign M_AXI_MEM1_awid = mm_awid[1*IDW +: IDW];
    assign M_AXI_MEM1_awaddr = mm_awaddr[1*AW +: AW];
    assign M_AXI_MEM1_awlen = mm_awlen[1*8 +: 8];
    assign M_AXI_MEM1_awsize = mm_awsize[1*3 +: 3];
    assign M_AXI_MEM1_awburst = mm_awburst[1*2 +: 2];
    assign M_AXI_MEM1_awvalid = mm_awvalid[1];
    assign mm_awready[1] = M_AXI_MEM1_awready;
    assign M_AXI_MEM1_wdata = mm_wdata[1*DW +: DW];
    assign M_AXI_MEM1_wstrb = mm_wstrb[1*DW/8 +: DW/8];
    assign M_AXI_MEM1_wlast = mm_wlast[1];
    assign M_AXI_MEM1_wvalid = mm_wvalid[1];
    assign mm_wready[1] = M_AXI_MEM1_wready;
    assign mm_bid[1*IDW +: IDW] = M_AXI_MEM1_bid;
    assign mm_bresp[1*2 +: 2] = M_AXI_MEM1_bresp;
    assign mm_bvalid[1] = M_AXI_MEM1_bvalid;
    assign M_AXI_MEM1_bready = mm_bready[1];
    assign M_AXI_MEM1_arid = mm_arid[1*IDW +: IDW];
    assign M_AXI_MEM1_araddr = mm_araddr[1*AW +: AW];
    assign M_AXI_MEM1_arlen = mm_arlen[1*8 +: 8];
    assign M_AXI_MEM1_arsize = mm_arsize[1*3 +: 3];
    assign M_AXI_MEM1_arburst = mm_arburst[1*2 +: 2];
    assign M_AXI_MEM1_arvalid = mm_arvalid[1];
    assign mm_arready[1] = M_AXI_MEM1_arready;
    assign mm_rid[1*IDW +: IDW] = M_AXI_MEM1_rid;
    assign mm_rdata[1*DW +: DW] = M_AXI_MEM1_rdata;
    assign mm_rresp[1*2 +: 2] = M_AXI_MEM1_rresp;
    assign mm_rlast[1] = M_AXI_MEM1_rlast;
    assign mm_rvalid[1] = M_AXI_MEM1_rvalid;
    assign M_AXI_MEM1_rready = mm_rready[1];
    assign M_AXI_MEM2_awid = mm_awid[2*IDW +: IDW];
    assign M_AXI_MEM2_awaddr = mm_awaddr[2*AW +: AW];
    assign M_AXI_MEM2_awlen = mm_awlen[2*8 +: 8];
    assign M_AXI_MEM2_awsize = mm_awsize[2*3 +: 3];
    assign M_AXI_MEM2_awburst = mm_awburst[2*2 +: 2];
    assign M_AXI_MEM2_awvalid = mm_awvalid[2];
    assign mm_awready[2] = M_AXI_MEM2_awready;
    assign M_AXI_MEM2_wdata = mm_wdata[2*DW +: DW];
    assign M_AXI_MEM2_wstrb = mm_wstrb[2*DW/8 +: DW/8];
    assign M_AXI_MEM2_wlast = mm_wlast[2];
    assign M_AXI_MEM2_wvalid = mm_wvalid[2];
    assign mm_wready[2] = M_AXI_MEM2_wready;
    assign mm_bid[2*IDW +: IDW] = M_AXI_MEM2_bid;
    assign mm_bresp[2*2 +: 2] = M_AXI_MEM2_bresp;
    assign mm_bvalid[2] = M_AXI_MEM2_bvalid;
    assign M_AXI_MEM2_bready = mm_bready[2];
    assign M_AXI_MEM2_arid = mm_arid[2*IDW +: IDW];
    assign M_AXI_MEM2_araddr = mm_araddr[2*AW +: AW];
    assign M_AXI_MEM2_arlen = mm_arlen[2*8 +: 8];
    assign M_AXI_MEM2_arsize = mm_arsize[2*3 +: 3];
    assign M_AXI_MEM2_arburst = mm_arburst[2*2 +: 2];
    assign M_AXI_MEM2_arvalid = mm_arvalid[2];
    assign mm_arready[2] = M_AXI_MEM2_arready;
    assign mm_rid[2*IDW +: IDW] = M_AXI_MEM2_rid;
    assign mm_rdata[2*DW +: DW] = M_AXI_MEM2_rdata;
    assign mm_rresp[2*2 +: 2] = M_AXI_MEM2_rresp;
    assign mm_rlast[2] = M_AXI_MEM2_rlast;
    assign mm_rvalid[2] = M_AXI_MEM2_rvalid;
    assign M_AXI_MEM2_rready = mm_rready[2];
    assign M_AXI_UPLOAD_awid = mm_awid[3*IDW +: IDW];
    assign M_AXI_UPLOAD_awaddr = mm_awaddr[3*AW +: AW];
    assign M_AXI_UPLOAD_awlen = mm_awlen[3*8 +: 8];
    assign M_AXI_UPLOAD_awsize = mm_awsize[3*3 +: 3];
    assign M_AXI_UPLOAD_awburst = mm_awburst[3*2 +: 2];
    assign M_AXI_UPLOAD_awvalid = mm_awvalid[3];
    assign mm_awready[3] = M_AXI_UPLOAD_awready;
    assign M_AXI_UPLOAD_wdata = mm_wdata[3*DW +: DW];
    assign M_AXI_UPLOAD_wstrb = mm_wstrb[3*DW/8 +: DW/8];
    assign M_AXI_UPLOAD_wlast = mm_wlast[3];
    assign M_AXI_UPLOAD_wvalid = mm_wvalid[3];
    assign mm_wready[3] = M_AXI_UPLOAD_wready;
    assign mm_bid[3*IDW +: IDW] = M_AXI_UPLOAD_bid;
    assign mm_bresp[3*2 +: 2] = M_AXI_UPLOAD_bresp;
    assign mm_bvalid[3] = M_AXI_UPLOAD_bvalid;
    assign M_AXI_UPLOAD_bready = mm_bready[3];
    assign M_AXI_UPLOAD_arid = mm_arid[3*IDW +: IDW];
    assign M_AXI_UPLOAD_araddr = mm_araddr[3*AW +: AW];
    assign M_AXI_UPLOAD_arlen = mm_arlen[3*8 +: 8];
    assign M_AXI_UPLOAD_arsize = mm_arsize[3*3 +: 3];
    assign M_AXI_UPLOAD_arburst = mm_arburst[3*2 +: 2];
    assign M_AXI_UPLOAD_arvalid = mm_arvalid[3];
    assign mm_arready[3] = M_AXI_UPLOAD_arready;
    assign mm_rid[3*IDW +: IDW] = M_AXI_UPLOAD_rid;
    assign mm_rdata[3*DW +: DW] = M_AXI_UPLOAD_rdata;
    assign mm_rresp[3*2 +: 2] = M_AXI_UPLOAD_rresp;
    assign mm_rlast[3] = M_AXI_UPLOAD_rlast;
    assign mm_rvalid[3] = M_AXI_UPLOAD_rvalid;
    assign M_AXI_UPLOAD_rready = mm_rready[3];
    assign M_AXI_MOVER_awid = mm_awid[4*IDW +: IDW];
    assign M_AXI_MOVER_awaddr = mm_awaddr[4*AW +: AW];
    assign M_AXI_MOVER_awlen = mm_awlen[4*8 +: 8];
    assign M_AXI_MOVER_awsize = mm_awsize[4*3 +: 3];
    assign M_AXI_MOVER_awburst = mm_awburst[4*2 +: 2];
    assign M_AXI_MOVER_awvalid = mm_awvalid[4];
    assign mm_awready[4] = M_AXI_MOVER_awready;
    assign M_AXI_MOVER_wdata = mm_wdata[4*DW +: DW];
    assign M_AXI_MOVER_wstrb = mm_wstrb[4*DW/8 +: DW/8];
    assign M_AXI_MOVER_wlast = mm_wlast[4];
    assign M_AXI_MOVER_wvalid = mm_wvalid[4];
    assign mm_wready[4] = M_AXI_MOVER_wready;
    assign mm_bid[4*IDW +: IDW] = M_AXI_MOVER_bid;
    assign mm_bresp[4*2 +: 2] = M_AXI_MOVER_bresp;
    assign mm_bvalid[4] = M_AXI_MOVER_bvalid;
    assign M_AXI_MOVER_bready = mm_bready[4];
    assign M_AXI_MOVER_arid = mm_arid[4*IDW +: IDW];
    assign M_AXI_MOVER_araddr = mm_araddr[4*AW +: AW];
    assign M_AXI_MOVER_arlen = mm_arlen[4*8 +: 8];
    assign M_AXI_MOVER_arsize = mm_arsize[4*3 +: 3];
    assign M_AXI_MOVER_arburst = mm_arburst[4*2 +: 2];
    assign M_AXI_MOVER_arvalid = mm_arvalid[4];
    assign mm_arready[4] = M_AXI_MOVER_arready;
    assign mm_rid[4*IDW +: IDW] = M_AXI_MOVER_rid;
    assign mm_rdata[4*DW +: DW] = M_AXI_MOVER_rdata;
    assign mm_rresp[4*2 +: 2] = M_AXI_MOVER_rresp;
    assign mm_rlast[4] = M_AXI_MOVER_rlast;
    assign mm_rvalid[4] = M_AXI_MOVER_rvalid;
    assign M_AXI_MOVER_rready = mm_rready[4];
    assign M_AXI_ILINK_awid = mm_awid[5*IDW +: IDW];
    assign M_AXI_ILINK_awaddr = mm_awaddr[5*AW +: AW];
    assign M_AXI_ILINK_awlen = mm_awlen[5*8 +: 8];
    assign M_AXI_ILINK_awsize = mm_awsize[5*3 +: 3];
    assign M_AXI_ILINK_awburst = mm_awburst[5*2 +: 2];
    assign M_AXI_ILINK_awvalid = mm_awvalid[5];
    assign mm_awready[5] = M_AXI_ILINK_awready;
    assign M_AXI_ILINK_wdata = mm_wdata[5*DW +: DW];
    assign M_AXI_ILINK_wstrb = mm_wstrb[5*DW/8 +: DW/8];
    assign M_AXI_ILINK_wlast = mm_wlast[5];
    assign M_AXI_ILINK_wvalid = mm_wvalid[5];
    assign mm_wready[5] = M_AXI_ILINK_wready;
    assign mm_bid[5*IDW +: IDW] = M_AXI_ILINK_bid;
    assign mm_bresp[5*2 +: 2] = M_AXI_ILINK_bresp;
    assign mm_bvalid[5] = M_AXI_ILINK_bvalid;
    assign M_AXI_ILINK_bready = mm_bready[5];
    assign M_AXI_ILINK_arid = mm_arid[5*IDW +: IDW];
    assign M_AXI_ILINK_araddr = mm_araddr[5*AW +: AW];
    assign M_AXI_ILINK_arlen = mm_arlen[5*8 +: 8];
    assign M_AXI_ILINK_arsize = mm_arsize[5*3 +: 3];
    assign M_AXI_ILINK_arburst = mm_arburst[5*2 +: 2];
    assign M_AXI_ILINK_arvalid = mm_arvalid[5];
    assign mm_arready[5] = M_AXI_ILINK_arready;
    assign mm_rid[5*IDW +: IDW] = M_AXI_ILINK_rid;
    assign mm_rdata[5*DW +: DW] = M_AXI_ILINK_rdata;
    assign mm_rresp[5*2 +: 2] = M_AXI_ILINK_rresp;
    assign mm_rlast[5] = M_AXI_ILINK_rlast;
    assign mm_rvalid[5] = M_AXI_ILINK_rvalid;
    assign M_AXI_ILINK_rready = mm_rready[5];

    wire [NMAG*FW-1:0] mag_o_d;
    wire [NMAG-1:0]    mag_i_v, mag_i_b, mag_o_v, mag_o_b;
    wire [15:0]        mag_rd, mag_wr;

    wire [15:0] cu_f [0:NCU-1];
    wire [15:0] cu_g [0:NCU-1];
    wire [15:0] cu_d [0:NCU-1];
    wire [31:0] vc_cyc [0:NVEC-1];
    wire        vc_flt [0:NVEC-1];

    // The mover is commanded through S_AXI_CTRL, so its status is internal and
    // reaches `obs` only to stop synthesis pruning it.
    wire        mv_busy;
    wire [3:0]  mv_fault;
    wire [31:0] mv_done;

    wire [FW-1:0] l000_h0_1_fd; wire l000_h0_1_fv; wire l000_h0_1_fb;
    wire [FW-1:0] l000_h0_1_rd; wire l000_h0_1_rv; wire l000_h0_1_rb;
    wire [FW-1:0] l001_h1_1_fd; wire l001_h1_1_fv; wire l001_h1_1_fb;
    wire [FW-1:0] l001_h1_1_rd; wire l001_h1_1_rv; wire l001_h1_1_rb;
    wire [FW-1:0] l002_v1_0_fd; wire l002_v1_0_fv; wire l002_v1_0_fb;
    wire [FW-1:0] l002_v1_0_rd; wire l002_v1_0_rv; wire l002_v1_0_rb;
    wire [FW-1:0] l003_v1_1_fd; wire l003_v1_1_fv; wire l003_v1_1_fb;
    wire [FW-1:0] l003_v1_1_rd; wire l003_v1_1_rv; wire l003_v1_1_rb;
    wire [FW-1:0] l004_L1_1_fd; wire l004_L1_1_fv; wire l004_L1_1_fb;
    wire [FW-1:0] l004_L1_1_rd; wire l004_L1_1_rv; wire l004_L1_1_rb;
    wire [FW-1:0] l005_h2_1_fd; wire l005_h2_1_fv; wire l005_h2_1_fb;
    wire [FW-1:0] l005_h2_1_rd; wire l005_h2_1_rv; wire l005_h2_1_rb;
    wire [FW-1:0] l006_v2_0_fd; wire l006_v2_0_fv; wire l006_v2_0_fb;
    wire [FW-1:0] l006_v2_0_rd; wire l006_v2_0_rv; wire l006_v2_0_rb;
    wire [FW-1:0] l007_v2_1_fd; wire l007_v2_1_fv; wire l007_v2_1_fb;
    wire [FW-1:0] l007_v2_1_rd; wire l007_v2_1_rv; wire l007_v2_1_rb;
    wire [FW-1:0] l008_L2_1_fd; wire l008_L2_1_fv; wire l008_L2_1_fb;
    wire [FW-1:0] l008_L2_1_rd; wire l008_L2_1_rv; wire l008_L2_1_rb;
    wire [FW-1:0] l009_h0_2_fd; wire l009_h0_2_fv; wire l009_h0_2_fb;
    wire [FW-1:0] l009_h0_2_rd; wire l009_h0_2_rv; wire l009_h0_2_rb;
    wire [FW-1:0] l010_h1_2_fd; wire l010_h1_2_fv; wire l010_h1_2_fb;
    wire [FW-1:0] l010_h1_2_rd; wire l010_h1_2_rv; wire l010_h1_2_rb;
    wire [FW-1:0] l011_v1_2_fd; wire l011_v1_2_fv; wire l011_v1_2_fb;
    wire [FW-1:0] l011_v1_2_rd; wire l011_v1_2_rv; wire l011_v1_2_rb;
    wire [FW-1:0] l012_L1_2_fd; wire l012_L1_2_fv; wire l012_L1_2_fb;
    wire [FW-1:0] l012_L1_2_rd; wire l012_L1_2_rv; wire l012_L1_2_rb;
    wire [FW-1:0] l013_h2_2_fd; wire l013_h2_2_fv; wire l013_h2_2_fb;
    wire [FW-1:0] l013_h2_2_rd; wire l013_h2_2_rv; wire l013_h2_2_rb;
    wire [FW-1:0] l014_v2_2_fd; wire l014_v2_2_fv; wire l014_v2_2_fb;
    wire [FW-1:0] l014_v2_2_rd; wire l014_v2_2_rv; wire l014_v2_2_rb;
    wire [FW-1:0] l015_L2_2_fd; wire l015_L2_2_fv; wire l015_L2_2_fb;
    wire [FW-1:0] l015_L2_2_rd; wire l015_L2_2_rv; wire l015_L2_2_rb;
    wire [FW-1:0] l016_h0_3_fd; wire l016_h0_3_fv; wire l016_h0_3_fb;
    wire [FW-1:0] l016_h0_3_rd; wire l016_h0_3_rv; wire l016_h0_3_rb;
    wire [FW-1:0] l017_h1_3_fd; wire l017_h1_3_fv; wire l017_h1_3_fb;
    wire [FW-1:0] l017_h1_3_rd; wire l017_h1_3_rv; wire l017_h1_3_rb;
    wire [FW-1:0] l018_v1_3_fd; wire l018_v1_3_fv; wire l018_v1_3_fb;
    wire [FW-1:0] l018_v1_3_rd; wire l018_v1_3_rv; wire l018_v1_3_rb;
    wire [FW-1:0] l019_L1_3_fd; wire l019_L1_3_fv; wire l019_L1_3_fb;
    wire [FW-1:0] l019_L1_3_rd; wire l019_L1_3_rv; wire l019_L1_3_rb;
    wire [FW-1:0] l020_h2_3_fd; wire l020_h2_3_fv; wire l020_h2_3_fb;
    wire [FW-1:0] l020_h2_3_rd; wire l020_h2_3_rv; wire l020_h2_3_rb;
    wire [FW-1:0] l021_v2_3_fd; wire l021_v2_3_fv; wire l021_v2_3_fb;
    wire [FW-1:0] l021_v2_3_rd; wire l021_v2_3_rv; wire l021_v2_3_rb;
    wire [FW-1:0] l022_L2_3_fd; wire l022_L2_3_fv; wire l022_L2_3_fb;
    wire [FW-1:0] l022_L2_3_rd; wire l022_L2_3_rv; wire l022_L2_3_rb;

    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(1), .POS_Y(1), .GRID_LO(1),
                .GRID_HI(3), .GRID_X_HI(2),
                .GRID_Y_HI(3)) r1_1 (
        .clk(clk), .rst(rst),
        .west_in_data(l000_h0_1_fd),   .west_in_valid(l000_h0_1_fv),   .west_in_busy(l000_h0_1_fb),
        .west_out_data(l000_h0_1_rd),  .west_out_valid(l000_h0_1_rv),  .west_out_busy(l000_h0_1_rb),
        .east_in_data(l001_h1_1_rd),   .east_in_valid(l001_h1_1_rv),   .east_in_busy(l001_h1_1_rb),
        .east_out_data(l001_h1_1_fd),  .east_out_valid(l001_h1_1_fv),  .east_out_busy(l001_h1_1_fb),
        .north_in_data(l002_v1_0_fd),  .north_in_valid(l002_v1_0_fv),  .north_in_busy(l002_v1_0_fb),
        .north_out_data(l002_v1_0_rd), .north_out_valid(l002_v1_0_rv), .north_out_busy(l002_v1_0_rb),
        .south_in_data(l003_v1_1_rd),  .south_in_valid(l003_v1_1_rv),  .south_in_busy(l003_v1_1_rb),
        .south_out_data(l003_v1_1_fd), .south_out_valid(l003_v1_1_fv), .south_out_busy(l003_v1_1_fb),
        .local_in_data(l004_L1_1_fd),  .local_in_valid(l004_L1_1_fv),  .local_in_busy(l004_L1_1_fb),
        .local_out_data(l004_L1_1_rd), .local_out_valid(l004_L1_1_rv), .local_out_busy(l004_L1_1_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(2), .POS_Y(1), .GRID_LO(1),
                .GRID_HI(3), .GRID_X_HI(2),
                .GRID_Y_HI(3)) r2_1 (
        .clk(clk), .rst(rst),
        .west_in_data(l001_h1_1_fd),   .west_in_valid(l001_h1_1_fv),   .west_in_busy(l001_h1_1_fb),
        .west_out_data(l001_h1_1_rd),  .west_out_valid(l001_h1_1_rv),  .west_out_busy(l001_h1_1_rb),
        .east_in_data(l005_h2_1_rd),   .east_in_valid(l005_h2_1_rv),   .east_in_busy(l005_h2_1_rb),
        .east_out_data(l005_h2_1_fd),  .east_out_valid(l005_h2_1_fv),  .east_out_busy(l005_h2_1_fb),
        .north_in_data(l006_v2_0_fd),  .north_in_valid(l006_v2_0_fv),  .north_in_busy(l006_v2_0_fb),
        .north_out_data(l006_v2_0_rd), .north_out_valid(l006_v2_0_rv), .north_out_busy(l006_v2_0_rb),
        .south_in_data(l007_v2_1_rd),  .south_in_valid(l007_v2_1_rv),  .south_in_busy(l007_v2_1_rb),
        .south_out_data(l007_v2_1_fd), .south_out_valid(l007_v2_1_fv), .south_out_busy(l007_v2_1_fb),
        .local_in_data(l008_L2_1_fd),  .local_in_valid(l008_L2_1_fv),  .local_in_busy(l008_L2_1_fb),
        .local_out_data(l008_L2_1_rd), .local_out_valid(l008_L2_1_rv), .local_out_busy(l008_L2_1_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(1), .POS_Y(2), .GRID_LO(1),
                .GRID_HI(3), .GRID_X_HI(2),
                .GRID_Y_HI(3)) r1_2 (
        .clk(clk), .rst(rst),
        .west_in_data(l009_h0_2_fd),   .west_in_valid(l009_h0_2_fv),   .west_in_busy(l009_h0_2_fb),
        .west_out_data(l009_h0_2_rd),  .west_out_valid(l009_h0_2_rv),  .west_out_busy(l009_h0_2_rb),
        .east_in_data(l010_h1_2_rd),   .east_in_valid(l010_h1_2_rv),   .east_in_busy(l010_h1_2_rb),
        .east_out_data(l010_h1_2_fd),  .east_out_valid(l010_h1_2_fv),  .east_out_busy(l010_h1_2_fb),
        .north_in_data(l003_v1_1_fd),  .north_in_valid(l003_v1_1_fv),  .north_in_busy(l003_v1_1_fb),
        .north_out_data(l003_v1_1_rd), .north_out_valid(l003_v1_1_rv), .north_out_busy(l003_v1_1_rb),
        .south_in_data(l011_v1_2_rd),  .south_in_valid(l011_v1_2_rv),  .south_in_busy(l011_v1_2_rb),
        .south_out_data(l011_v1_2_fd), .south_out_valid(l011_v1_2_fv), .south_out_busy(l011_v1_2_fb),
        .local_in_data(l012_L1_2_fd),  .local_in_valid(l012_L1_2_fv),  .local_in_busy(l012_L1_2_fb),
        .local_out_data(l012_L1_2_rd), .local_out_valid(l012_L1_2_rv), .local_out_busy(l012_L1_2_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(2), .POS_Y(2), .GRID_LO(1),
                .GRID_HI(3), .GRID_X_HI(2),
                .GRID_Y_HI(3)) r2_2 (
        .clk(clk), .rst(rst),
        .west_in_data(l010_h1_2_fd),   .west_in_valid(l010_h1_2_fv),   .west_in_busy(l010_h1_2_fb),
        .west_out_data(l010_h1_2_rd),  .west_out_valid(l010_h1_2_rv),  .west_out_busy(l010_h1_2_rb),
        .east_in_data(l013_h2_2_rd),   .east_in_valid(l013_h2_2_rv),   .east_in_busy(l013_h2_2_rb),
        .east_out_data(l013_h2_2_fd),  .east_out_valid(l013_h2_2_fv),  .east_out_busy(l013_h2_2_fb),
        .north_in_data(l007_v2_1_fd),  .north_in_valid(l007_v2_1_fv),  .north_in_busy(l007_v2_1_fb),
        .north_out_data(l007_v2_1_rd), .north_out_valid(l007_v2_1_rv), .north_out_busy(l007_v2_1_rb),
        .south_in_data(l014_v2_2_rd),  .south_in_valid(l014_v2_2_rv),  .south_in_busy(l014_v2_2_rb),
        .south_out_data(l014_v2_2_fd), .south_out_valid(l014_v2_2_fv), .south_out_busy(l014_v2_2_fb),
        .local_in_data(l015_L2_2_fd),  .local_in_valid(l015_L2_2_fv),  .local_in_busy(l015_L2_2_fb),
        .local_out_data(l015_L2_2_rd), .local_out_valid(l015_L2_2_rv), .local_out_busy(l015_L2_2_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(1), .POS_Y(3), .GRID_LO(1),
                .GRID_HI(3), .GRID_X_HI(2),
                .GRID_Y_HI(3)) r1_3 (
        .clk(clk), .rst(rst),
        .west_in_data(l016_h0_3_fd),   .west_in_valid(l016_h0_3_fv),   .west_in_busy(l016_h0_3_fb),
        .west_out_data(l016_h0_3_rd),  .west_out_valid(l016_h0_3_rv),  .west_out_busy(l016_h0_3_rb),
        .east_in_data(l017_h1_3_rd),   .east_in_valid(l017_h1_3_rv),   .east_in_busy(l017_h1_3_rb),
        .east_out_data(l017_h1_3_fd),  .east_out_valid(l017_h1_3_fv),  .east_out_busy(l017_h1_3_fb),
        .north_in_data(l011_v1_2_fd),  .north_in_valid(l011_v1_2_fv),  .north_in_busy(l011_v1_2_fb),
        .north_out_data(l011_v1_2_rd), .north_out_valid(l011_v1_2_rv), .north_out_busy(l011_v1_2_rb),
        .south_in_data(l018_v1_3_rd),  .south_in_valid(l018_v1_3_rv),  .south_in_busy(l018_v1_3_rb),
        .south_out_data(l018_v1_3_fd), .south_out_valid(l018_v1_3_fv), .south_out_busy(l018_v1_3_fb),
        .local_in_data(l019_L1_3_fd),  .local_in_valid(l019_L1_3_fv),  .local_in_busy(l019_L1_3_fb),
        .local_out_data(l019_L1_3_rd), .local_out_valid(l019_L1_3_rv), .local_out_busy(l019_L1_3_rb)
    );
    NoCRouter #(.DATA_WIDTH(FW), .FIFO_DEPTH(512),
                .MEMORY_TYPE("block"), .POS_WIDTH(PW),
                .POS_X(2), .POS_Y(3), .GRID_LO(1),
                .GRID_HI(3), .GRID_X_HI(2),
                .GRID_Y_HI(3)) r2_3 (
        .clk(clk), .rst(rst),
        .west_in_data(l017_h1_3_fd),   .west_in_valid(l017_h1_3_fv),   .west_in_busy(l017_h1_3_fb),
        .west_out_data(l017_h1_3_rd),  .west_out_valid(l017_h1_3_rv),  .west_out_busy(l017_h1_3_rb),
        .east_in_data(l020_h2_3_rd),   .east_in_valid(l020_h2_3_rv),   .east_in_busy(l020_h2_3_rb),
        .east_out_data(l020_h2_3_fd),  .east_out_valid(l020_h2_3_fv),  .east_out_busy(l020_h2_3_fb),
        .north_in_data(l014_v2_2_fd),  .north_in_valid(l014_v2_2_fv),  .north_in_busy(l014_v2_2_fb),
        .north_out_data(l014_v2_2_rd), .north_out_valid(l014_v2_2_rv), .north_out_busy(l014_v2_2_rb),
        .south_in_data(l021_v2_3_rd),  .south_in_valid(l021_v2_3_rv),  .south_in_busy(l021_v2_3_rb),
        .south_out_data(l021_v2_3_fd), .south_out_valid(l021_v2_3_fv), .south_out_busy(l021_v2_3_fb),
        .local_in_data(l022_L2_3_fd),  .local_in_valid(l022_L2_3_fv),  .local_in_busy(l022_L2_3_fb),
        .local_out_data(l022_L2_3_rd), .local_out_valid(l022_L2_3_rv), .local_out_busy(l022_L2_3_rb)
    );
    assign l000_h0_1_fv = mag_o_v[0];
    assign mag_o_b[0] = l000_h0_1_fb;
    assign mag_i_v[0] = l000_h0_1_rv;
    assign l000_h0_1_rb = mag_i_b[0];
    assign l009_h0_2_fv = mag_o_v[1];
    assign mag_o_b[1] = l009_h0_2_fb;
    assign mag_i_v[1] = l009_h0_2_rv;
    assign l009_h0_2_rb = mag_i_b[1];
    assign l016_h0_3_fv = mag_o_v[2];
    assign mag_o_b[2] = l016_h0_3_fb;
    assign mag_i_v[2] = l016_h0_3_rv;
    assign l016_h0_3_rb = mag_i_b[2];
    assign l000_h0_1_fd = mag_o_d[0*FW +: FW];
    assign l009_h0_2_fd = mag_o_d[1*FW +: FW];
    assign l016_h0_3_fd = mag_o_d[2*FW +: FW];
    mag #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .DATA_W(DW), .ADDR_W(AW),
          .ID_W(IDW), .MEM_PORTS(3), .MEM_X(0), .MEM_Y(1), .MEM_X1(0), .MEM_Y1(2), .MEM_X2(0), .MEM_Y2(3),
          .GRID_LO(1), .GRID_HI(3), .STAGE_FLITS(128),
          .ILINK(1), .MESH_ID(MESH_ID), .LINK_W(LKW), .TUSER_W(LKU)) u_mag (
        .clk(clk), .resetn(resetn),
        .sm_awid(S_AXI_MEM_awid), .sm_awaddr(S_AXI_MEM_awaddr),
        .sm_awlen(S_AXI_MEM_awlen), .sm_awvalid(S_AXI_MEM_awvalid),
        .sm_awready(S_AXI_MEM_awready),
        .sm_wdata(S_AXI_MEM_wdata), .sm_wstrb(S_AXI_MEM_wstrb),
        .sm_wlast(S_AXI_MEM_wlast), .sm_wvalid(S_AXI_MEM_wvalid),
        .sm_wready(S_AXI_MEM_wready),
        .sm_bid(S_AXI_MEM_bid), .sm_bresp(S_AXI_MEM_bresp),
        .sm_bvalid(S_AXI_MEM_bvalid), .sm_bready(S_AXI_MEM_bready),
        .sm_arid(S_AXI_MEM_arid), .sm_araddr(S_AXI_MEM_araddr),
        .sm_arlen(S_AXI_MEM_arlen), .sm_arvalid(S_AXI_MEM_arvalid),
        .sm_arready(S_AXI_MEM_arready),
        .sm_rid(S_AXI_MEM_rid), .sm_rdata(S_AXI_MEM_rdata),
        .sm_rresp(S_AXI_MEM_rresp), .sm_rlast(S_AXI_MEM_rlast),
        .sm_rvalid(S_AXI_MEM_rvalid), .sm_rready(S_AXI_MEM_rready),
        .sc_awid(S_AXI_CTRL_awid), .sc_awaddr(S_AXI_CTRL_awaddr),
        .sc_awlen(S_AXI_CTRL_awlen), .sc_awvalid(S_AXI_CTRL_awvalid),
        .sc_awready(S_AXI_CTRL_awready),
        .sc_wdata(S_AXI_CTRL_wdata), .sc_wstrb(S_AXI_CTRL_wstrb),
        .sc_wlast(S_AXI_CTRL_wlast), .sc_wvalid(S_AXI_CTRL_wvalid),
        .sc_wready(S_AXI_CTRL_wready),
        .sc_bid(S_AXI_CTRL_bid), .sc_bresp(S_AXI_CTRL_bresp),
        .sc_bvalid(S_AXI_CTRL_bvalid), .sc_bready(S_AXI_CTRL_bready),
        .sc_arid(S_AXI_CTRL_arid), .sc_araddr(S_AXI_CTRL_araddr),
        .sc_arlen(S_AXI_CTRL_arlen), .sc_arvalid(S_AXI_CTRL_arvalid),
        .sc_arready(S_AXI_CTRL_arready),
        .sc_rid(S_AXI_CTRL_rid), .sc_rdata(S_AXI_CTRL_rdata),
        .sc_rresp(S_AXI_CTRL_rresp), .sc_rlast(S_AXI_CTRL_rlast),
        .sc_rvalid(S_AXI_CTRL_rvalid), .sc_rready(S_AXI_CTRL_rready),
        .m_awid(mm_awid), .m_awaddr(mm_awaddr), .m_awlen(mm_awlen),
        .m_awsize(mm_awsize), .m_awburst(mm_awburst),
        .m_awvalid(mm_awvalid), .m_awready(mm_awready),
        .m_wdata(mm_wdata), .m_wstrb(mm_wstrb), .m_wlast(mm_wlast),
        .m_wvalid(mm_wvalid), .m_wready(mm_wready),
        .m_bid(mm_bid), .m_bresp(mm_bresp), .m_bvalid(mm_bvalid), .m_bready(mm_bready),
        .m_arid(mm_arid), .m_araddr(mm_araddr), .m_arlen(mm_arlen),
        .m_arsize(mm_arsize), .m_arburst(mm_arburst),
        .m_arvalid(mm_arvalid), .m_arready(mm_arready),
        .m_rid(mm_rid), .m_rdata(mm_rdata), .m_rresp(mm_rresp),
        .m_rlast(mm_rlast), .m_rvalid(mm_rvalid), .m_rready(mm_rready),
        .link0_out_tdata(M_AXIS_LINK0_tdata), .link0_out_tuser(M_AXIS_LINK0_tuser),
        .link0_out_tlast(M_AXIS_LINK0_tlast), .link0_out_tvalid(M_AXIS_LINK0_tvalid),
        .link0_out_tready(M_AXIS_LINK0_tready),
        .link0_in_tdata(S_AXIS_LINK0_tdata), .link0_in_tuser(S_AXIS_LINK0_tuser),
        .link0_in_tlast(S_AXIS_LINK0_tlast), .link0_in_tvalid(S_AXIS_LINK0_tvalid),
        .link0_in_tready(S_AXIS_LINK0_tready),
        .link1_out_tdata(M_AXIS_LINK1_tdata), .link1_out_tuser(M_AXIS_LINK1_tuser),
        .link1_out_tlast(M_AXIS_LINK1_tlast), .link1_out_tvalid(M_AXIS_LINK1_tvalid),
        .link1_out_tready(M_AXIS_LINK1_tready),
        .link1_in_tdata(S_AXIS_LINK1_tdata), .link1_in_tuser(S_AXIS_LINK1_tuser),
        .link1_in_tlast(S_AXIS_LINK1_tlast), .link1_in_tvalid(S_AXIS_LINK1_tvalid),
        .link1_in_tready(S_AXIS_LINK1_tready),
        .mem_in_data({l016_h0_3_rd, l009_h0_2_rd, l000_h0_1_rd}), .mem_in_valid(mag_i_v), .mem_in_busy(mag_i_b),
        .mem_out_data(mag_o_d), .mem_out_valid(mag_o_v), .mem_out_busy(mag_o_b),
        .mem_rd_count(mag_rd), .mem_wr_count(mag_wr),
        .mv_busy(mv_busy), .mv_fault(mv_fault), .mv_done(mv_done)
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(1), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(1), .MODEL(MODEL)) u_cu0 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l004_L1_1_fd), .noc_out_valid(l004_L1_1_fv), .noc_out_busy(l004_L1_1_fb), .noc_in_data(l004_L1_1_rd), .noc_in_valid(l004_L1_1_rv), .noc_in_busy(l004_L1_1_rb),
        .fills_done(cu_f[0]), .gemms_done(cu_g[0]), .drains_done(cu_d[0])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(2), .CU_Y(1), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(1), .MODEL(MODEL)) u_cu1 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l008_L2_1_fd), .noc_out_valid(l008_L2_1_fv), .noc_out_busy(l008_L2_1_fb), .noc_in_data(l008_L2_1_rd), .noc_in_valid(l008_L2_1_rv), .noc_in_busy(l008_L2_1_rb),
        .fills_done(cu_f[1]), .gemms_done(cu_g[1]), .drains_done(cu_d[1])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(2), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(2), .MODEL(MODEL)) u_cu2 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l012_L1_2_fd), .noc_out_valid(l012_L1_2_fv), .noc_out_busy(l012_L1_2_fb), .noc_in_data(l012_L1_2_rd), .noc_in_valid(l012_L1_2_rv), .noc_in_busy(l012_L1_2_rb),
        .fills_done(cu_f[2]), .gemms_done(cu_g[2]), .drains_done(cu_d[2])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(2), .CU_Y(2), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(2), .MODEL(MODEL)) u_cu3 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l015_L2_2_fd), .noc_out_valid(l015_L2_2_fv), .noc_out_busy(l015_L2_2_fb), .noc_in_data(l015_L2_2_rd), .noc_in_valid(l015_L2_2_rv), .noc_in_busy(l015_L2_2_rb),
        .fills_done(cu_f[3]), .gemms_done(cu_g[3]), .drains_done(cu_d[3])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(1), .CU_Y(3), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(3), .MODEL(MODEL)) u_cu4 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l019_L1_3_fd), .noc_out_valid(l019_L1_3_fv), .noc_out_busy(l019_L1_3_fb), .noc_in_data(l019_L1_3_rd), .noc_in_valid(l019_L1_3_rv), .noc_in_busy(l019_L1_3_rb),
        .fills_done(cu_f[4]), .gemms_done(cu_g[4]), .drains_done(cu_d[4])
    );
    mx_cluster_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW),
                    .CU_X(2), .CU_Y(3), .TILES(TILES), .GA(GA), .GB(GB),
                    .L1_PRIM(L1_PRIM),
                    .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
                    .MEM_X(0), .MEM_Y(3), .MODEL(MODEL)) u_cu5 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l022_L2_3_fd), .noc_out_valid(l022_L2_3_fv), .noc_out_busy(l022_L2_3_fb), .noc_in_data(l022_L2_3_rd), .noc_in_valid(l022_L2_3_rv), .noc_in_busy(l022_L2_3_rb),
        .fills_done(cu_f[5]), .gemms_done(cu_g[5]), .drains_done(cu_d[5])
    );
    vec_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .POS_X(1), .POS_Y(0),
             .MEM_X(0), .MEM_Y(1), .MODEL(MODEL),
             .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
             .L1_DEPTH(L1_DEPTH), .L1_PRIM("block")) u_vec0 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l002_v1_0_fd), .noc_out_valid(l002_v1_0_fv), .noc_out_busy(l002_v1_0_fb), .noc_in_data(l002_v1_0_rd), .noc_in_valid(l002_v1_0_rv), .noc_in_busy(l002_v1_0_rb),
        .dbg_cycles(vc_cyc[0]), .dbg_fault(vc_flt[0])
    );
    vec_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .POS_X(2), .POS_Y(0),
             .MEM_X(0), .MEM_Y(1), .MODEL(MODEL),
             .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
             .L1_DEPTH(L1_DEPTH), .L1_PRIM("block")) u_vec1 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l006_v2_0_fd), .noc_out_valid(l006_v2_0_fv), .noc_out_busy(l006_v2_0_fb), .noc_in_data(l006_v2_0_rd), .noc_in_valid(l006_v2_0_rv), .noc_in_busy(l006_v2_0_rb),
        .dbg_cycles(vc_cyc[1]), .dbg_fault(vc_flt[1])
    );
    vec_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .POS_X(1), .POS_Y(4),
             .MEM_X(0), .MEM_Y(3), .MODEL(MODEL),
             .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
             .L1_DEPTH(L1_DEPTH), .L1_PRIM("block")) u_vec2 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l018_v1_3_rd), .noc_out_valid(l018_v1_3_rv), .noc_out_busy(l018_v1_3_rb), .noc_in_data(l018_v1_3_fd), .noc_in_valid(l018_v1_3_fv), .noc_in_busy(l018_v1_3_fb),
        .dbg_cycles(vc_cyc[2]), .dbg_fault(vc_flt[2])
    );
    vec_cu #(.FLIT_WIDTH(FW), .POS_WIDTH(PW), .POS_X(2), .POS_Y(4),
             .MEM_X(0), .MEM_Y(3), .MODEL(MODEL),
             .INST_DEPTH(INST_DEPTH), .RECV_DEPTH(RECV_DEPTH),
             .L1_DEPTH(L1_DEPTH), .L1_PRIM("block")) u_vec3 (
        .clk(clk), .resetn(resetn),
        .noc_out_data(l021_v2_3_rd), .noc_out_valid(l021_v2_3_rv), .noc_out_busy(l021_v2_3_rb), .noc_in_data(l021_v2_3_fd), .noc_in_valid(l021_v2_3_fv), .noc_in_busy(l021_v2_3_fb),
        .dbg_cycles(vc_cyc[3]), .dbg_fault(vc_flt[3])
    );
    assign l005_h2_1_rd = {FW{1'b0}}; assign l005_h2_1_rv = 1'b0; assign l005_h2_1_fb = 1'b0;
    assign l013_h2_2_rd = {FW{1'b0}}; assign l013_h2_2_rv = 1'b0; assign l013_h2_2_fb = 1'b0;
    assign l020_h2_3_rd = {FW{1'b0}}; assign l020_h2_3_rv = 1'b0; assign l020_h2_3_fb = 1'b0;

    // The boundary is clock, reset and AXI. There is deliberately no `obs`
    // fold: it existed to stop synthesis pruning these counters, which no
    // software can read, so it was keeping dead logic alive and inflating
    // every measurement taken through it. Pruning them is the right answer.

endmodule

`default_nettype wire
