// Transcendental coefficient ROMs for the vector ALU.
//
// GENERATED by scripts/py/vec_tables.py -- do not edit by hand. That script is
// also the golden model: it evaluates the same two Horner stages in integer
// arithmetic, so a mismatch with vec_alu.v shows up as a bench failure.
//
//   u   12-bit unsigned, weight 2^-12
//   c2  22-bit signed, weight 2^-28
//   c1  22-bit signed, weight 2^-24
//   c0  22-bit signed, weight 2^-20
//
//   h = (c2*u + (c1<<16) + 2^15) >> 16
//   F = (h *u + (c0<<16) + 2^15) >> 16
//
// Measured worst-case absolute error of the circuit above against the real
// function, over a dense sweep of every segment:
//
//   exp2   2^-19.9    (3.9 bits of margin over the E8M15 half-ulp)
//   log2   2^-19.5    (3.5 bits of margin over the E8M15 half-ulp)
//   inv    2^-19.4    (3.4 bits of margin over the E8M15 half-ulp)
//   rsqrt  2^-19.8    (3.8 bits of margin over the E8M15 half-ulp)
//
// The fit is UNCONSTRAINED, segment 0 included. The identity cases
//   exp2(k)==2^k   log2(2^k)==k   inv(2^k)==2^-k   rsqrt(2^even)
// are forced in vec_alu.v instead, by a mux on F. Constraining the
// polynomial through g(0) costs 1.5 bits -- see fit_quadratic().

`default_nettype none

module vec_tables (
    input  wire               clk,
    input  wire [1:0]         fsel,   // 0 exp2, 1 log2, 2 inv, 3 rsqrt
    input  wire [5:0]         idx,    // idx[5] is the octave parity, rsqrt only
    // SYNCHRONOUS, and rom_style names the primitive rather than leaving
    // it to a heuristic. The one cycle of latency is stated by the RTL, and
    // vec_alu drops its own u_d_ix stage to pay for it -- the address was
    // already registered, so this is a register MOVE and cycle 3 is
    // still when c0/c1/c2 land. 3,568 LUT per core -> 16 RAMB36.
    (* rom_style = "block" *) output reg signed [21:0] c0,
    (* rom_style = "block" *) output reg signed [21:0] c1,
    (* rom_style = "block" *) output reg signed [21:0] c2
);
    // One flat case over {fsel, idx}, constant-indexed throughout.
    // NON-BLOCKING: u_d_c1 in vec_alu registers c1 on the same edge, so
    // blocking assignments here are a scheduler race, not a style point.
    always @(posedge clk) begin
        case ({fsel, idx})
        // ---- exp2 ----
        8'd0  : begin c0 <= 22'sd0 ; c1 <= 22'sd363393 ; c2 <= 22'sd63660 ; end
        8'd1  : begin c0 <= 22'sd22961 ; c1 <= 22'sd371350 ; c2 <= 22'sd65054 ; end
        8'd2  : begin c0 <= 22'sd46424 ; c1 <= 22'sd379481 ; c2 <= 22'sd66479 ; end
        8'd3  : begin c0 <= 22'sd70402 ; c1 <= 22'sd387791 ; c2 <= 22'sd67934 ; end
        8'd4  : begin c0 <= 22'sd94904 ; c1 <= 22'sd396282 ; c2 <= 22'sd69422 ; end
        8'd5  : begin c0 <= 22'sd119943 ; c1 <= 22'sd404960 ; c2 <= 22'sd70942 ; end
        8'd6  : begin c0 <= 22'sd145530 ; c1 <= 22'sd413827 ; c2 <= 22'sd72495 ; end
        8'd7  : begin c0 <= 22'sd171678 ; c1 <= 22'sd422889 ; c2 <= 22'sd74083 ; end
        8'd8  : begin c0 <= 22'sd198398 ; c1 <= 22'sd432149 ; c2 <= 22'sd75705 ; end
        8'd9  : begin c0 <= 22'sd225703 ; c1 <= 22'sd441612 ; c2 <= 22'sd77363 ; end
        8'd10 : begin c0 <= 22'sd253606 ; c1 <= 22'sd451282 ; c2 <= 22'sd79057 ; end
        8'd11 : begin c0 <= 22'sd282120 ; c1 <= 22'sd461164 ; c2 <= 22'sd80788 ; end
        8'd12 : begin c0 <= 22'sd311259 ; c1 <= 22'sd471262 ; c2 <= 22'sd82557 ; end
        8'd13 : begin c0 <= 22'sd341035 ; c1 <= 22'sd481581 ; c2 <= 22'sd84365 ; end
        8'd14 : begin c0 <= 22'sd371464 ; c1 <= 22'sd492126 ; c2 <= 22'sd86212 ; end
        8'd15 : begin c0 <= 22'sd402559 ; c1 <= 22'sd502903 ; c2 <= 22'sd88100 ; end
        8'd16 : begin c0 <= 22'sd434334 ; c1 <= 22'sd513915 ; c2 <= 22'sd90029 ; end
        8'd17 : begin c0 <= 22'sd466806 ; c1 <= 22'sd525168 ; c2 <= 22'sd92000 ; end
        8'd18 : begin c0 <= 22'sd499989 ; c1 <= 22'sd536668 ; c2 <= 22'sd94015 ; end
        8'd19 : begin c0 <= 22'sd533898 ; c1 <= 22'sd548419 ; c2 <= 22'sd96074 ; end
        8'd20 : begin c0 <= 22'sd568549 ; c1 <= 22'sd560428 ; c2 <= 22'sd98177 ; end
        8'd21 : begin c0 <= 22'sd603960 ; c1 <= 22'sd572700 ; c2 <= 22'sd100327 ; end
        8'd22 : begin c0 <= 22'sd640146 ; c1 <= 22'sd585240 ; c2 <= 22'sd102524 ; end
        8'd23 : begin c0 <= 22'sd677124 ; c1 <= 22'sd598055 ; c2 <= 22'sd104769 ; end
        8'd24 : begin c0 <= 22'sd714912 ; c1 <= 22'sd611151 ; c2 <= 22'sd107063 ; end
        8'd25 : begin c0 <= 22'sd753527 ; c1 <= 22'sd624534 ; c2 <= 22'sd109408 ; end
        8'd26 : begin c0 <= 22'sd792988 ; c1 <= 22'sd638209 ; c2 <= 22'sd111803 ; end
        8'd27 : begin c0 <= 22'sd833313 ; c1 <= 22'sd652184 ; c2 <= 22'sd114251 ; end
        8'd28 : begin c0 <= 22'sd874521 ; c1 <= 22'sd666465 ; c2 <= 22'sd116753 ; end
        8'd29 : begin c0 <= 22'sd916631 ; c1 <= 22'sd681059 ; c2 <= 22'sd119310 ; end
        8'd30 : begin c0 <= 22'sd959664 ; c1 <= 22'sd695972 ; c2 <= 22'sd121922 ; end
        8'd31 : begin c0 <= 22'sd1003638 ; c1 <= 22'sd711212 ; c2 <= 22'sd124592 ; end
        // ---- log2 ----
        8'd64 : begin c0 <= 22'sd0 ; c1 <= 22'sd756254 ; c2 <= -22'sd183340 ; end
        8'd65 : begin c0 <= 22'sd46551 ; c1 <= 22'sd733345 ; c2 <= -22'sd172556 ; end
        8'd66 : begin c0 <= 22'sd91712 ; c1 <= 22'sd711782 ; c2 <= -22'sd162697 ; end
        8'd67 : begin c0 <= 22'sd135563 ; c1 <= 22'sd691452 ; c2 <= -22'sd153660 ; end
        8'd68 : begin c0 <= 22'sd178180 ; c1 <= 22'sd672250 ; c2 <= -22'sd145355 ; end
        8'd69 : begin c0 <= 22'sd219628 ; c1 <= 22'sd654086 ; c2 <= -22'sd137705 ; end
        8'd70 : begin c0 <= 22'sd259971 ; c1 <= 22'sd636878 ; c2 <= -22'sd130644 ; end
        8'd71 : begin c0 <= 22'sd299266 ; c1 <= 22'sd620551 ; c2 <= -22'sd124113 ; end
        8'd72 : begin c0 <= 22'sd337566 ; c1 <= 22'sd605041 ; c2 <= -22'sd118059 ; end
        8'd73 : begin c0 <= 22'sd374921 ; c1 <= 22'sd590287 ; c2 <= -22'sd112438 ; end
        8'd74 : begin c0 <= 22'sd411375 ; c1 <= 22'sd576236 ; c2 <= -22'sd107208 ; end
        8'd75 : begin c0 <= 22'sd446971 ; c1 <= 22'sd562837 ; c2 <= -22'sd102336 ; end
        8'd76 : begin c0 <= 22'sd481749 ; c1 <= 22'sd550048 ; c2 <= -22'sd97788 ; end
        8'd77 : begin c0 <= 22'sd515746 ; c1 <= 22'sd537827 ; c2 <= -22'sd93537 ; end
        8'd78 : begin c0 <= 22'sd548995 ; c1 <= 22'sd526137 ; c2 <= -22'sd89557 ; end
        8'd79 : begin c0 <= 22'sd581529 ; c1 <= 22'sd514945 ; c2 <= -22'sd85825 ; end
        8'd80 : begin c0 <= 22'sd613378 ; c1 <= 22'sd504218 ; c2 <= -22'sd82322 ; end
        8'd81 : begin c0 <= 22'sd644570 ; c1 <= 22'sd493930 ; c2 <= -22'sd79030 ; end
        8'd82 : begin c0 <= 22'sd675132 ; c1 <= 22'sd484053 ; c2 <= -22'sd75931 ; end
        8'd83 : begin c0 <= 22'sd705089 ; c1 <= 22'sd474563 ; c2 <= -22'sd73010 ; end
        8'd84 : begin c0 <= 22'sd734464 ; c1 <= 22'sd465438 ; c2 <= -22'sd70256 ; end
        8'd85 : begin c0 <= 22'sd763280 ; c1 <= 22'sd456657 ; c2 <= -22'sd67654 ; end
        8'd86 : begin c0 <= 22'sd791557 ; c1 <= 22'sd448201 ; c2 <= -22'sd65194 ; end
        8'd87 : begin c0 <= 22'sd819315 ; c1 <= 22'sd440053 ; c2 <= -22'sd62865 ; end
        8'd88 : begin c0 <= 22'sd846573 ; c1 <= 22'sd432196 ; c2 <= -22'sd60660 ; end
        8'd89 : begin c0 <= 22'sd873349 ; c1 <= 22'sd424615 ; c2 <= -22'sd58568 ; end
        8'd90 : begin c0 <= 22'sd899658 ; c1 <= 22'sd417295 ; c2 <= -22'sd56583 ; end
        8'd91 : begin c0 <= 22'sd925518 ; c1 <= 22'sd410222 ; c2 <= -22'sd54697 ; end
        8'd92 : begin c0 <= 22'sd950944 ; c1 <= 22'sd403386 ; c2 <= -22'sd52904 ; end
        8'd93 : begin c0 <= 22'sd975949 ; c1 <= 22'sd396774 ; c2 <= -22'sd51197 ; end
        8'd94 : begin c0 <= 22'sd1000547 ; c1 <= 22'sd390375 ; c2 <= -22'sd49572 ; end
        8'd95 : begin c0 <= 22'sd1024752 ; c1 <= 22'sd384179 ; c2 <= -22'sd48023 ; end
        // ---- inv ----
        8'd128: begin c0 <= 22'sd1048575 ; c1 <= -22'sd524013 ; c2 <= 22'sd250275 ; end
        8'd129: begin c0 <= 22'sd1016800 ; c1 <= -22'sd492751 ; c2 <= 22'sd228522 ; end
        8'd130: begin c0 <= 22'sd986894 ; c1 <= -22'sd464205 ; c2 <= 22'sd209219 ; end
        8'd131: begin c0 <= 22'sd958697 ; c1 <= -22'sd438069 ; c2 <= 22'sd192030 ; end
        8'd132: begin c0 <= 22'sd932067 ; c1 <= -22'sd414079 ; c2 <= 22'sd176674 ; end
        8'd133: begin c0 <= 22'sd906876 ; c1 <= -22'sd392008 ; c2 <= 22'sd162912 ; end
        8'd134: begin c0 <= 22'sd883011 ; c1 <= -22'sd371655 ; c2 <= 22'sd150544 ; end
        8'd135: begin c0 <= 22'sd860370 ; c1 <= -22'sd352846 ; c2 <= 22'sd139396 ; end
        8'd136: begin c0 <= 22'sd838860 ; c1 <= -22'sd335430 ; c2 <= 22'sd129323 ; end
        8'd137: begin c0 <= 22'sd818400 ; c1 <= -22'sd319273 ; c2 <= 22'sd120197 ; end
        8'd138: begin c0 <= 22'sd798915 ; c1 <= -22'sd304255 ; c2 <= 22'sd111910 ; end
        8'd139: begin c0 <= 22'sd780335 ; c1 <= -22'sd290272 ; c2 <= 22'sd104367 ; end
        8'd140: begin c0 <= 22'sd762600 ; c1 <= -22'sd277231 ; c2 <= 22'sd97488 ; end
        8'd141: begin c0 <= 22'sd745654 ; c1 <= -22'sd265050 ; c2 <= 22'sd91200 ; end
        8'd142: begin c0 <= 22'sd729444 ; c1 <= -22'sd253654 ; c2 <= 22'sd85441 ; end
        8'd143: begin c0 <= 22'sd713924 ; c1 <= -22'sd242978 ; c2 <= 22'sd80158 ; end
        8'd144: begin c0 <= 22'sd699050 ; c1 <= -22'sd232962 ; c2 <= 22'sd75301 ; end
        8'd145: begin c0 <= 22'sd684784 ; c1 <= -22'sd223552 ; c2 <= 22'sd70828 ; end
        8'd146: begin c0 <= 22'sd671088 ; c1 <= -22'sd214701 ; c2 <= 22'sd66703 ; end
        8'd147: begin c0 <= 22'sd657930 ; c1 <= -22'sd206366 ; c2 <= 22'sd62893 ; end
        8'd148: begin c0 <= 22'sd645277 ; c1 <= -22'sd198507 ; c2 <= 22'sd59367 ; end
        8'd149: begin c0 <= 22'sd633102 ; c1 <= -22'sd191088 ; c2 <= 22'sd56099 ; end
        8'd150: begin c0 <= 22'sd621378 ; c1 <= -22'sd184078 ; c2 <= 22'sd53067 ; end
        8'd151: begin c0 <= 22'sd610080 ; c1 <= -22'sd177446 ; c2 <= 22'sd50250 ; end
        8'd152: begin c0 <= 22'sd599186 ; c1 <= -22'sd171166 ; c2 <= 22'sd47629 ; end
        8'd153: begin c0 <= 22'sd588674 ; c1 <= -22'sd165214 ; c2 <= 22'sd45187 ; end
        8'd154: begin c0 <= 22'sd578525 ; c1 <= -22'sd159567 ; c2 <= 22'sd42909 ; end
        8'd155: begin c0 <= 22'sd568719 ; c1 <= -22'sd154205 ; c2 <= 22'sd40781 ; end
        8'd156: begin c0 <= 22'sd559240 ; c1 <= -22'sd149108 ; c2 <= 22'sd38792 ; end
        8'd157: begin c0 <= 22'sd550073 ; c1 <= -22'sd144260 ; c2 <= 22'sd36931 ; end
        8'd158: begin c0 <= 22'sd541200 ; c1 <= -22'sd139645 ; c2 <= 22'sd35186 ; end
        8'd159: begin c0 <= 22'sd532610 ; c1 <= -22'sd135247 ; c2 <= 22'sd33550 ; end
        // ---- rsqrt ----
        8'd192: begin c0 <= 22'sd1048576 ; c1 <= -22'sd262057 ; c2 <= 22'sd94579 ; end
        8'd193: begin c0 <= 22'sd1032566 ; c1 <= -22'sd250241 ; c2 <= 22'sd87677 ; end
        8'd194: begin c0 <= 22'sd1017268 ; c1 <= -22'sd239287 ; c2 <= 22'sd81461 ; end
        8'd195: begin c0 <= 22'sd1002630 ; c1 <= -22'sd229109 ; c2 <= 22'sd75844 ; end
        8'd196: begin c0 <= 22'sd988607 ; c1 <= -22'sd219633 ; c2 <= 22'sd70755 ; end
        8'd197: begin c0 <= 22'sd975156 ; c1 <= -22'sd210792 ; c2 <= 22'sd66132 ; end
        8'd198: begin c0 <= 22'sd962239 ; c1 <= -22'sd202529 ; c2 <= 22'sd61920 ; end
        8'd199: begin c0 <= 22'sd949823 ; c1 <= -22'sd194792 ; c2 <= 22'sd58075 ; end
        8'd200: begin c0 <= 22'sd937875 ; c1 <= -22'sd187535 ; c2 <= 22'sd54556 ; end
        8'd201: begin c0 <= 22'sd926367 ; c1 <= -22'sd180718 ; c2 <= 22'sd51329 ; end
        8'd202: begin c0 <= 22'sd915272 ; c1 <= -22'sd174304 ; c2 <= 22'sd48362 ; end
        8'd203: begin c0 <= 22'sd904567 ; c1 <= -22'sd168260 ; c2 <= 22'sd45630 ; end
        8'd204: begin c0 <= 22'sd894229 ; c1 <= -22'sd162558 ; c2 <= 22'sd43110 ; end
        8'd205: begin c0 <= 22'sd884237 ; c1 <= -22'sd157171 ; c2 <= 22'sd40780 ; end
        8'd206: begin c0 <= 22'sd874573 ; c1 <= -22'sd152075 ; c2 <= 22'sd38623 ; end
        8'd207: begin c0 <= 22'sd865219 ; c1 <= -22'sd147248 ; c2 <= 22'sd36622 ; end
        8'd208: begin c0 <= 22'sd856159 ; c1 <= -22'sd142672 ; c2 <= 22'sd34763 ; end
        8'd209: begin c0 <= 22'sd847377 ; c1 <= -22'sd138328 ; c2 <= 22'sd33034 ; end
        8'd210: begin c0 <= 22'sd838861 ; c1 <= -22'sd134199 ; c2 <= 22'sd31423 ; end
        8'd211: begin c0 <= 22'sd830596 ; c1 <= -22'sd130272 ; c2 <= 22'sd29919 ; end
        8'd212: begin c0 <= 22'sd822571 ; c1 <= -22'sd126533 ; c2 <= 22'sd28515 ; end
        8'd213: begin c0 <= 22'sd814774 ; c1 <= -22'sd122970 ; c2 <= 22'sd27201 ; end
        8'd214: begin c0 <= 22'sd807194 ; c1 <= -22'sd119570 ; c2 <= 22'sd25970 ; end
        8'd215: begin c0 <= 22'sd799822 ; c1 <= -22'sd116325 ; c2 <= 22'sd24816 ; end
        8'd216: begin c0 <= 22'sd792649 ; c1 <= -22'sd113223 ; c2 <= 22'sd23733 ; end
        8'd217: begin c0 <= 22'sd785665 ; c1 <= -22'sd110257 ; c2 <= 22'sd22714 ; end
        8'd218: begin c0 <= 22'sd778863 ; c1 <= -22'sd107418 ; c2 <= 22'sd21756 ; end
        8'd219: begin c0 <= 22'sd772234 ; c1 <= -22'sd104699 ; c2 <= 22'sd20853 ; end
        8'd220: begin c0 <= 22'sd765772 ; c1 <= -22'sd102093 ; c2 <= 22'sd20002 ; end
        8'd221: begin c0 <= 22'sd759469 ; c1 <= -22'sd99593 ; c2 <= 22'sd19199 ; end
        8'd222: begin c0 <= 22'sd753319 ; c1 <= -22'sd97194 ; c2 <= 22'sd18440 ; end
        8'd223: begin c0 <= 22'sd747317 ; c1 <= -22'sd94889 ; c2 <= 22'sd17723 ; end
        8'd224: begin c0 <= 22'sd741455 ; c1 <= -22'sd185303 ; c2 <= 22'sd66877 ; end
        8'd225: begin c0 <= 22'sd730134 ; c1 <= -22'sd176947 ; c2 <= 22'sd61997 ; end
        8'd226: begin c0 <= 22'sd719317 ; c1 <= -22'sd169201 ; c2 <= 22'sd57601 ; end
        8'd227: begin c0 <= 22'sd708967 ; c1 <= -22'sd162005 ; c2 <= 22'sd53630 ; end
        8'd228: begin c0 <= 22'sd699051 ; c1 <= -22'sd155304 ; c2 <= 22'sd50032 ; end
        8'd229: begin c0 <= 22'sd689539 ; c1 <= -22'sd149053 ; c2 <= 22'sd46762 ; end
        8'd230: begin c0 <= 22'sd680406 ; c1 <= -22'sd143210 ; c2 <= 22'sd43784 ; end
        8'd231: begin c0 <= 22'sd671626 ; c1 <= -22'sd137739 ; c2 <= 22'sd41065 ; end
        8'd232: begin c0 <= 22'sd663178 ; c1 <= -22'sd132607 ; c2 <= 22'sd38577 ; end
        8'd233: begin c0 <= 22'sd655040 ; c1 <= -22'sd127787 ; c2 <= 22'sd36295 ; end
        8'd234: begin c0 <= 22'sd647195 ; c1 <= -22'sd123251 ; c2 <= 22'sd34197 ; end
        8'd235: begin c0 <= 22'sd639625 ; c1 <= -22'sd118978 ; c2 <= 22'sd32266 ; end
        8'd236: begin c0 <= 22'sd632315 ; c1 <= -22'sd114946 ; c2 <= 22'sd30483 ; end
        8'd237: begin c0 <= 22'sd625250 ; c1 <= -22'sd111137 ; c2 <= 22'sd28836 ; end
        8'd238: begin c0 <= 22'sd618416 ; c1 <= -22'sd107533 ; c2 <= 22'sd27310 ; end
        8'd239: begin c0 <= 22'sd611802 ; c1 <= -22'sd104120 ; c2 <= 22'sd25895 ; end
        8'd240: begin c0 <= 22'sd605396 ; c1 <= -22'sd100884 ; c2 <= 22'sd24581 ; end
        8'd241: begin c0 <= 22'sd599186 ; c1 <= -22'sd97812 ; c2 <= 22'sd23358 ; end
        8'd242: begin c0 <= 22'sd593164 ; c1 <= -22'sd94893 ; c2 <= 22'sd22219 ; end
        8'd243: begin c0 <= 22'sd587320 ; c1 <= -22'sd92116 ; c2 <= 22'sd21156 ; end
        8'd244: begin c0 <= 22'sd581645 ; c1 <= -22'sd89473 ; c2 <= 22'sd20163 ; end
        8'd245: begin c0 <= 22'sd576132 ; c1 <= -22'sd86953 ; c2 <= 22'sd19234 ; end
        8'd246: begin c0 <= 22'sd570772 ; c1 <= -22'sd84549 ; c2 <= 22'sd18364 ; end
        8'd247: begin c0 <= 22'sd565560 ; c1 <= -22'sd82254 ; c2 <= 22'sd17548 ; end
        8'd248: begin c0 <= 22'sd560487 ; c1 <= -22'sd80061 ; c2 <= 22'sd16781 ; end
        8'd249: begin c0 <= 22'sd555549 ; c1 <= -22'sd77964 ; c2 <= 22'sd16061 ; end
        8'd250: begin c0 <= 22'sd550739 ; c1 <= -22'sd75956 ; c2 <= 22'sd15384 ; end
        8'd251: begin c0 <= 22'sd546052 ; c1 <= -22'sd74034 ; c2 <= 22'sd14745 ; end
        8'd252: begin c0 <= 22'sd541482 ; c1 <= -22'sd72191 ; c2 <= 22'sd14144 ; end
        8'd253: begin c0 <= 22'sd537026 ; c1 <= -22'sd70423 ; c2 <= 22'sd13576 ; end
        8'd254: begin c0 <= 22'sd532677 ; c1 <= -22'sd68726 ; c2 <= 22'sd13039 ; end
        8'd255: begin c0 <= 22'sd528433 ; c1 <= -22'sd67097 ; c2 <= 22'sd12532 ; end
        default: begin c0 <= 22'sd0 ; c1 <= 22'sd0 ; c2 <= 22'sd0 ; end
        endcase
    end
endmodule

`default_nettype wire
