[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kohakutpu"
version = "0.0.1"
description = "Host driver for KohakuTPU"
authors = [
    { name = "Shih-Ying Yeh(KohakuBlueLeaf)", email = "apolloyeh0123@gmail.com" },
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff"]

[tool.setuptools]
package-dir = { "" = "src" }
